// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

/**
 * Protobuf type {@code com.github.paohaijiao.proto.JQuickColumnStatsProto}
 */
public final class JQuickColumnStatsProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.paohaijiao.proto.JQuickColumnStatsProto)
    JQuickColumnStatsProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JQuickColumnStatsProto.newBuilder() to construct.
  private JQuickColumnStatsProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JQuickColumnStatsProto() {
    minValue_ = com.google.protobuf.ByteString.EMPTY;
    maxValue_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JQuickColumnStatsProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickColumnStatsProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickColumnStatsProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.paohaijiao.proto.JQuickColumnStatsProto.class, com.github.paohaijiao.proto.JQuickColumnStatsProto.Builder.class);
  }

  public static final int DISTINCT_COUNT_FIELD_NUMBER = 1;
  private long distinctCount_ = 0L;
  /**
   * <code>int64 distinct_count = 1;</code>
   * @return The distinctCount.
   */
  @java.lang.Override
  public long getDistinctCount() {
    return distinctCount_;
  }

  public static final int MIN_VALUE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString minValue_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes min_value = 2;</code>
   * @return The minValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMinValue() {
    return minValue_;
  }

  public static final int MAX_VALUE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString maxValue_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes max_value = 3;</code>
   * @return The maxValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMaxValue() {
    return maxValue_;
  }

  public static final int NULL_FRACTION_FIELD_NUMBER = 4;
  private double nullFraction_ = 0D;
  /**
   * <code>double null_fraction = 4;</code>
   * @return The nullFraction.
   */
  @java.lang.Override
  public double getNullFraction() {
    return nullFraction_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (distinctCount_ != 0L) {
      output.writeInt64(1, distinctCount_);
    }
    if (!minValue_.isEmpty()) {
      output.writeBytes(2, minValue_);
    }
    if (!maxValue_.isEmpty()) {
      output.writeBytes(3, maxValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(nullFraction_) != 0) {
      output.writeDouble(4, nullFraction_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (distinctCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, distinctCount_);
    }
    if (!minValue_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, minValue_);
    }
    if (!maxValue_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, maxValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(nullFraction_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, nullFraction_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.paohaijiao.proto.JQuickColumnStatsProto)) {
      return super.equals(obj);
    }
    com.github.paohaijiao.proto.JQuickColumnStatsProto other = (com.github.paohaijiao.proto.JQuickColumnStatsProto) obj;

    if (getDistinctCount()
        != other.getDistinctCount()) return false;
    if (!getMinValue()
        .equals(other.getMinValue())) return false;
    if (!getMaxValue()
        .equals(other.getMaxValue())) return false;
    if (java.lang.Double.doubleToLongBits(getNullFraction())
        != java.lang.Double.doubleToLongBits(
            other.getNullFraction())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISTINCT_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDistinctCount());
    hash = (37 * hash) + MIN_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getMinValue().hashCode();
    hash = (37 * hash) + MAX_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getMaxValue().hashCode();
    hash = (37 * hash) + NULL_FRACTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNullFraction()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickColumnStatsProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.paohaijiao.proto.JQuickColumnStatsProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.paohaijiao.proto.JQuickColumnStatsProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.paohaijiao.proto.JQuickColumnStatsProto)
      com.github.paohaijiao.proto.JQuickColumnStatsProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickColumnStatsProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickColumnStatsProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.paohaijiao.proto.JQuickColumnStatsProto.class, com.github.paohaijiao.proto.JQuickColumnStatsProto.Builder.class);
    }

    // Construct using com.github.paohaijiao.proto.JQuickColumnStatsProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      distinctCount_ = 0L;
      minValue_ = com.google.protobuf.ByteString.EMPTY;
      maxValue_ = com.google.protobuf.ByteString.EMPTY;
      nullFraction_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickColumnStatsProto_descriptor;
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickColumnStatsProto getDefaultInstanceForType() {
      return com.github.paohaijiao.proto.JQuickColumnStatsProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickColumnStatsProto build() {
      com.github.paohaijiao.proto.JQuickColumnStatsProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickColumnStatsProto buildPartial() {
      com.github.paohaijiao.proto.JQuickColumnStatsProto result = new com.github.paohaijiao.proto.JQuickColumnStatsProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.paohaijiao.proto.JQuickColumnStatsProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.distinctCount_ = distinctCount_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.minValue_ = minValue_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.maxValue_ = maxValue_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.nullFraction_ = nullFraction_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.paohaijiao.proto.JQuickColumnStatsProto) {
        return mergeFrom((com.github.paohaijiao.proto.JQuickColumnStatsProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.paohaijiao.proto.JQuickColumnStatsProto other) {
      if (other == com.github.paohaijiao.proto.JQuickColumnStatsProto.getDefaultInstance()) return this;
      if (other.getDistinctCount() != 0L) {
        setDistinctCount(other.getDistinctCount());
      }
      if (other.getMinValue() != com.google.protobuf.ByteString.EMPTY) {
        setMinValue(other.getMinValue());
      }
      if (other.getMaxValue() != com.google.protobuf.ByteString.EMPTY) {
        setMaxValue(other.getMaxValue());
      }
      if (other.getNullFraction() != 0D) {
        setNullFraction(other.getNullFraction());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              distinctCount_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              minValue_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              maxValue_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 33: {
              nullFraction_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long distinctCount_ ;
    /**
     * <code>int64 distinct_count = 1;</code>
     * @return The distinctCount.
     */
    @java.lang.Override
    public long getDistinctCount() {
      return distinctCount_;
    }
    /**
     * <code>int64 distinct_count = 1;</code>
     * @param value The distinctCount to set.
     * @return This builder for chaining.
     */
    public Builder setDistinctCount(long value) {
      
      distinctCount_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 distinct_count = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistinctCount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      distinctCount_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString minValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes min_value = 2;</code>
     * @return The minValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMinValue() {
      return minValue_;
    }
    /**
     * <code>bytes min_value = 2;</code>
     * @param value The minValue to set.
     * @return This builder for chaining.
     */
    public Builder setMinValue(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      minValue_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes min_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      minValue_ = getDefaultInstance().getMinValue();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString maxValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes max_value = 3;</code>
     * @return The maxValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMaxValue() {
      return maxValue_;
    }
    /**
     * <code>bytes max_value = 3;</code>
     * @param value The maxValue to set.
     * @return This builder for chaining.
     */
    public Builder setMaxValue(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      maxValue_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bytes max_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxValue() {
      bitField0_ = (bitField0_ & ~0x00000004);
      maxValue_ = getDefaultInstance().getMaxValue();
      onChanged();
      return this;
    }

    private double nullFraction_ ;
    /**
     * <code>double null_fraction = 4;</code>
     * @return The nullFraction.
     */
    @java.lang.Override
    public double getNullFraction() {
      return nullFraction_;
    }
    /**
     * <code>double null_fraction = 4;</code>
     * @param value The nullFraction to set.
     * @return This builder for chaining.
     */
    public Builder setNullFraction(double value) {
      
      nullFraction_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double null_fraction = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNullFraction() {
      bitField0_ = (bitField0_ & ~0x00000008);
      nullFraction_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.paohaijiao.proto.JQuickColumnStatsProto)
  }

  // @@protoc_insertion_point(class_scope:com.github.paohaijiao.proto.JQuickColumnStatsProto)
  private static final com.github.paohaijiao.proto.JQuickColumnStatsProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.paohaijiao.proto.JQuickColumnStatsProto();
  }

  public static com.github.paohaijiao.proto.JQuickColumnStatsProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JQuickColumnStatsProto>
      PARSER = new com.google.protobuf.AbstractParser<JQuickColumnStatsProto>() {
    @java.lang.Override
    public JQuickColumnStatsProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JQuickColumnStatsProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JQuickColumnStatsProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickColumnStatsProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

