// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

/**
 * <pre>
 * 执行任务响应
 * </pre>
 *
 * Protobuf type {@code com.github.paohaijiao.proto.JQuickExecuteTaskResponse}
 */
public final class JQuickExecuteTaskResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.paohaijiao.proto.JQuickExecuteTaskResponse)
    JQuickExecuteTaskResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JQuickExecuteTaskResponse.newBuilder() to construct.
  private JQuickExecuteTaskResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JQuickExecuteTaskResponse() {
    taskId_ = "";
    status_ = 0;
    errorMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JQuickExecuteTaskResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickExecuteTaskResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 9:
        return internalGetTaskMetrics();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickExecuteTaskResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.paohaijiao.proto.JQuickExecuteTaskResponse.class, com.github.paohaijiao.proto.JQuickExecuteTaskResponse.Builder.class);
  }

  public static final int TASK_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object taskId_ = "";
  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_ = 0;
  /**
   * <code>.com.github.paohaijiao.proto.JQuickTaskStatusProto status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.github.paohaijiao.proto.JQuickTaskStatusProto status = 2;</code>
   * @return The status.
   */
  @java.lang.Override public com.github.paohaijiao.proto.JQuickTaskStatusProto getStatus() {
    com.github.paohaijiao.proto.JQuickTaskStatusProto result = com.github.paohaijiao.proto.JQuickTaskStatusProto.forNumber(status_);
    return result == null ? com.github.paohaijiao.proto.JQuickTaskStatusProto.UNRECOGNIZED : result;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULT_DATA_FIELD_NUMBER = 4;
  private com.github.paohaijiao.proto.JQuickDataSetProto resultData_;
  /**
   * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
   * @return Whether the resultData field is set.
   */
  @java.lang.Override
  public boolean hasResultData() {
    return resultData_ != null;
  }
  /**
   * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
   * @return The resultData.
   */
  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickDataSetProto getResultData() {
    return resultData_ == null ? com.github.paohaijiao.proto.JQuickDataSetProto.getDefaultInstance() : resultData_;
  }
  /**
   * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
   */
  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickDataSetProtoOrBuilder getResultDataOrBuilder() {
    return resultData_ == null ? com.github.paohaijiao.proto.JQuickDataSetProto.getDefaultInstance() : resultData_;
  }

  public static final int EXECUTION_STATS_FIELD_NUMBER = 5;
  private com.github.paohaijiao.proto.JQuickPhysicalStatsProto executionStats_;
  /**
   * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
   * @return Whether the executionStats field is set.
   */
  @java.lang.Override
  public boolean hasExecutionStats() {
    return executionStats_ != null;
  }
  /**
   * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
   * @return The executionStats.
   */
  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickPhysicalStatsProto getExecutionStats() {
    return executionStats_ == null ? com.github.paohaijiao.proto.JQuickPhysicalStatsProto.getDefaultInstance() : executionStats_;
  }
  /**
   * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
   */
  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickPhysicalStatsProtoOrBuilder getExecutionStatsOrBuilder() {
    return executionStats_ == null ? com.github.paohaijiao.proto.JQuickPhysicalStatsProto.getDefaultInstance() : executionStats_;
  }

  public static final int PROCESSED_ROWS_FIELD_NUMBER = 6;
  private long processedRows_ = 0L;
  /**
   * <code>int64 processed_rows = 6;</code>
   * @return The processedRows.
   */
  @java.lang.Override
  public long getProcessedRows() {
    return processedRows_;
  }

  public static final int EXECUTION_TIME_MS_FIELD_NUMBER = 7;
  private long executionTimeMs_ = 0L;
  /**
   * <code>int64 execution_time_ms = 7;</code>
   * @return The executionTimeMs.
   */
  @java.lang.Override
  public long getExecutionTimeMs() {
    return executionTimeMs_;
  }

  public static final int MEMORY_USED_BYTES_FIELD_NUMBER = 8;
  private long memoryUsedBytes_ = 0L;
  /**
   * <pre>
   * 实际使用的内存
   * </pre>
   *
   * <code>int64 memory_used_bytes = 8;</code>
   * @return The memoryUsedBytes.
   */
  @java.lang.Override
  public long getMemoryUsedBytes() {
    return memoryUsedBytes_;
  }

  public static final int TASK_METRICS_FIELD_NUMBER = 9;
  private static final class TaskMetricsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickExecuteTaskResponse_TaskMetricsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> taskMetrics_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTaskMetrics() {
    if (taskMetrics_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TaskMetricsDefaultEntryHolder.defaultEntry);
    }
    return taskMetrics_;
  }
  public int getTaskMetricsCount() {
    return internalGetTaskMetrics().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; task_metrics = 9;</code>
   */
  @java.lang.Override
  public boolean containsTaskMetrics(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTaskMetrics().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTaskMetricsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTaskMetrics() {
    return getTaskMetricsMap();
  }
  /**
   * <code>map&lt;string, string&gt; task_metrics = 9;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getTaskMetricsMap() {
    return internalGetTaskMetrics().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; task_metrics = 9;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getTaskMetricsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTaskMetrics().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; task_metrics = 9;</code>
   */
  @java.lang.Override
  public java.lang.String getTaskMetricsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTaskMetrics().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
    }
    if (status_ != com.github.paohaijiao.proto.JQuickTaskStatusProto.TASK_PENDING.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMessage_);
    }
    if (resultData_ != null) {
      output.writeMessage(4, getResultData());
    }
    if (executionStats_ != null) {
      output.writeMessage(5, getExecutionStats());
    }
    if (processedRows_ != 0L) {
      output.writeInt64(6, processedRows_);
    }
    if (executionTimeMs_ != 0L) {
      output.writeInt64(7, executionTimeMs_);
    }
    if (memoryUsedBytes_ != 0L) {
      output.writeInt64(8, memoryUsedBytes_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTaskMetrics(),
        TaskMetricsDefaultEntryHolder.defaultEntry,
        9);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
    }
    if (status_ != com.github.paohaijiao.proto.JQuickTaskStatusProto.TASK_PENDING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMessage_);
    }
    if (resultData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getResultData());
    }
    if (executionStats_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getExecutionStats());
    }
    if (processedRows_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, processedRows_);
    }
    if (executionTimeMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, executionTimeMs_);
    }
    if (memoryUsedBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, memoryUsedBytes_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTaskMetrics().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      taskMetrics__ = TaskMetricsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, taskMetrics__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.paohaijiao.proto.JQuickExecuteTaskResponse)) {
      return super.equals(obj);
    }
    com.github.paohaijiao.proto.JQuickExecuteTaskResponse other = (com.github.paohaijiao.proto.JQuickExecuteTaskResponse) obj;

    if (!getTaskId()
        .equals(other.getTaskId())) return false;
    if (status_ != other.status_) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (hasResultData() != other.hasResultData()) return false;
    if (hasResultData()) {
      if (!getResultData()
          .equals(other.getResultData())) return false;
    }
    if (hasExecutionStats() != other.hasExecutionStats()) return false;
    if (hasExecutionStats()) {
      if (!getExecutionStats()
          .equals(other.getExecutionStats())) return false;
    }
    if (getProcessedRows()
        != other.getProcessedRows()) return false;
    if (getExecutionTimeMs()
        != other.getExecutionTimeMs()) return false;
    if (getMemoryUsedBytes()
        != other.getMemoryUsedBytes()) return false;
    if (!internalGetTaskMetrics().equals(
        other.internalGetTaskMetrics())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    if (hasResultData()) {
      hash = (37 * hash) + RESULT_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getResultData().hashCode();
    }
    if (hasExecutionStats()) {
      hash = (37 * hash) + EXECUTION_STATS_FIELD_NUMBER;
      hash = (53 * hash) + getExecutionStats().hashCode();
    }
    hash = (37 * hash) + PROCESSED_ROWS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProcessedRows());
    hash = (37 * hash) + EXECUTION_TIME_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExecutionTimeMs());
    hash = (37 * hash) + MEMORY_USED_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMemoryUsedBytes());
    if (!internalGetTaskMetrics().getMap().isEmpty()) {
      hash = (37 * hash) + TASK_METRICS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTaskMetrics().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.paohaijiao.proto.JQuickExecuteTaskResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 执行任务响应
   * </pre>
   *
   * Protobuf type {@code com.github.paohaijiao.proto.JQuickExecuteTaskResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.paohaijiao.proto.JQuickExecuteTaskResponse)
      com.github.paohaijiao.proto.JQuickExecuteTaskResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickExecuteTaskResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 9:
          return internalGetTaskMetrics();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 9:
          return internalGetMutableTaskMetrics();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickExecuteTaskResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.paohaijiao.proto.JQuickExecuteTaskResponse.class, com.github.paohaijiao.proto.JQuickExecuteTaskResponse.Builder.class);
    }

    // Construct using com.github.paohaijiao.proto.JQuickExecuteTaskResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      taskId_ = "";
      status_ = 0;
      errorMessage_ = "";
      resultData_ = null;
      if (resultDataBuilder_ != null) {
        resultDataBuilder_.dispose();
        resultDataBuilder_ = null;
      }
      executionStats_ = null;
      if (executionStatsBuilder_ != null) {
        executionStatsBuilder_.dispose();
        executionStatsBuilder_ = null;
      }
      processedRows_ = 0L;
      executionTimeMs_ = 0L;
      memoryUsedBytes_ = 0L;
      internalGetMutableTaskMetrics().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickExecuteTaskResponse_descriptor;
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickExecuteTaskResponse getDefaultInstanceForType() {
      return com.github.paohaijiao.proto.JQuickExecuteTaskResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickExecuteTaskResponse build() {
      com.github.paohaijiao.proto.JQuickExecuteTaskResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickExecuteTaskResponse buildPartial() {
      com.github.paohaijiao.proto.JQuickExecuteTaskResponse result = new com.github.paohaijiao.proto.JQuickExecuteTaskResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.paohaijiao.proto.JQuickExecuteTaskResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.taskId_ = taskId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.resultData_ = resultDataBuilder_ == null
            ? resultData_
            : resultDataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.executionStats_ = executionStatsBuilder_ == null
            ? executionStats_
            : executionStatsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.processedRows_ = processedRows_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.executionTimeMs_ = executionTimeMs_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.memoryUsedBytes_ = memoryUsedBytes_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.taskMetrics_ = internalGetTaskMetrics();
        result.taskMetrics_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.paohaijiao.proto.JQuickExecuteTaskResponse) {
        return mergeFrom((com.github.paohaijiao.proto.JQuickExecuteTaskResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.paohaijiao.proto.JQuickExecuteTaskResponse other) {
      if (other == com.github.paohaijiao.proto.JQuickExecuteTaskResponse.getDefaultInstance()) return this;
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasResultData()) {
        mergeResultData(other.getResultData());
      }
      if (other.hasExecutionStats()) {
        mergeExecutionStats(other.getExecutionStats());
      }
      if (other.getProcessedRows() != 0L) {
        setProcessedRows(other.getProcessedRows());
      }
      if (other.getExecutionTimeMs() != 0L) {
        setExecutionTimeMs(other.getExecutionTimeMs());
      }
      if (other.getMemoryUsedBytes() != 0L) {
        setMemoryUsedBytes(other.getMemoryUsedBytes());
      }
      internalGetMutableTaskMetrics().mergeFrom(
          other.internalGetTaskMetrics());
      bitField0_ |= 0x00000100;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              taskId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getResultDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getExecutionStatsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              processedRows_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              executionTimeMs_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              memoryUsedBytes_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              taskMetrics__ = input.readMessage(
                  TaskMetricsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableTaskMetrics().getMutableMap().put(
                  taskMetrics__.getKey(), taskMetrics__.getValue());
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object taskId_ = "";
    /**
     * <code>string task_id = 1;</code>
     * @return The taskId.
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_id = 1;</code>
     * @return The bytes for taskId.
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_id = 1;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      taskId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      taskId_ = getDefaultInstance().getTaskId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 1;</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      taskId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.com.github.paohaijiao.proto.JQuickTaskStatusProto status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickTaskStatusProto status = 2;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickTaskStatusProto status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickTaskStatusProto getStatus() {
      com.github.paohaijiao.proto.JQuickTaskStatusProto result = com.github.paohaijiao.proto.JQuickTaskStatusProto.forNumber(status_);
      return result == null ? com.github.paohaijiao.proto.JQuickTaskStatusProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickTaskStatusProto status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.github.paohaijiao.proto.JQuickTaskStatusProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickTaskStatusProto status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 3;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_message = 3;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_message = 3;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 3;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.github.paohaijiao.proto.JQuickDataSetProto resultData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.paohaijiao.proto.JQuickDataSetProto, com.github.paohaijiao.proto.JQuickDataSetProto.Builder, com.github.paohaijiao.proto.JQuickDataSetProtoOrBuilder> resultDataBuilder_;
    /**
     * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
     * @return Whether the resultData field is set.
     */
    public boolean hasResultData() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
     * @return The resultData.
     */
    public com.github.paohaijiao.proto.JQuickDataSetProto getResultData() {
      if (resultDataBuilder_ == null) {
        return resultData_ == null ? com.github.paohaijiao.proto.JQuickDataSetProto.getDefaultInstance() : resultData_;
      } else {
        return resultDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
     */
    public Builder setResultData(com.github.paohaijiao.proto.JQuickDataSetProto value) {
      if (resultDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resultData_ = value;
      } else {
        resultDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
     */
    public Builder setResultData(
        com.github.paohaijiao.proto.JQuickDataSetProto.Builder builderForValue) {
      if (resultDataBuilder_ == null) {
        resultData_ = builderForValue.build();
      } else {
        resultDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
     */
    public Builder mergeResultData(com.github.paohaijiao.proto.JQuickDataSetProto value) {
      if (resultDataBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          resultData_ != null &&
          resultData_ != com.github.paohaijiao.proto.JQuickDataSetProto.getDefaultInstance()) {
          getResultDataBuilder().mergeFrom(value);
        } else {
          resultData_ = value;
        }
      } else {
        resultDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
     */
    public Builder clearResultData() {
      bitField0_ = (bitField0_ & ~0x00000008);
      resultData_ = null;
      if (resultDataBuilder_ != null) {
        resultDataBuilder_.dispose();
        resultDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
     */
    public com.github.paohaijiao.proto.JQuickDataSetProto.Builder getResultDataBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getResultDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
     */
    public com.github.paohaijiao.proto.JQuickDataSetProtoOrBuilder getResultDataOrBuilder() {
      if (resultDataBuilder_ != null) {
        return resultDataBuilder_.getMessageOrBuilder();
      } else {
        return resultData_ == null ?
            com.github.paohaijiao.proto.JQuickDataSetProto.getDefaultInstance() : resultData_;
      }
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.paohaijiao.proto.JQuickDataSetProto, com.github.paohaijiao.proto.JQuickDataSetProto.Builder, com.github.paohaijiao.proto.JQuickDataSetProtoOrBuilder> 
        getResultDataFieldBuilder() {
      if (resultDataBuilder_ == null) {
        resultDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.paohaijiao.proto.JQuickDataSetProto, com.github.paohaijiao.proto.JQuickDataSetProto.Builder, com.github.paohaijiao.proto.JQuickDataSetProtoOrBuilder>(
                getResultData(),
                getParentForChildren(),
                isClean());
        resultData_ = null;
      }
      return resultDataBuilder_;
    }

    private com.github.paohaijiao.proto.JQuickPhysicalStatsProto executionStats_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.paohaijiao.proto.JQuickPhysicalStatsProto, com.github.paohaijiao.proto.JQuickPhysicalStatsProto.Builder, com.github.paohaijiao.proto.JQuickPhysicalStatsProtoOrBuilder> executionStatsBuilder_;
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
     * @return Whether the executionStats field is set.
     */
    public boolean hasExecutionStats() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
     * @return The executionStats.
     */
    public com.github.paohaijiao.proto.JQuickPhysicalStatsProto getExecutionStats() {
      if (executionStatsBuilder_ == null) {
        return executionStats_ == null ? com.github.paohaijiao.proto.JQuickPhysicalStatsProto.getDefaultInstance() : executionStats_;
      } else {
        return executionStatsBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
     */
    public Builder setExecutionStats(com.github.paohaijiao.proto.JQuickPhysicalStatsProto value) {
      if (executionStatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        executionStats_ = value;
      } else {
        executionStatsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
     */
    public Builder setExecutionStats(
        com.github.paohaijiao.proto.JQuickPhysicalStatsProto.Builder builderForValue) {
      if (executionStatsBuilder_ == null) {
        executionStats_ = builderForValue.build();
      } else {
        executionStatsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
     */
    public Builder mergeExecutionStats(com.github.paohaijiao.proto.JQuickPhysicalStatsProto value) {
      if (executionStatsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          executionStats_ != null &&
          executionStats_ != com.github.paohaijiao.proto.JQuickPhysicalStatsProto.getDefaultInstance()) {
          getExecutionStatsBuilder().mergeFrom(value);
        } else {
          executionStats_ = value;
        }
      } else {
        executionStatsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
     */
    public Builder clearExecutionStats() {
      bitField0_ = (bitField0_ & ~0x00000010);
      executionStats_ = null;
      if (executionStatsBuilder_ != null) {
        executionStatsBuilder_.dispose();
        executionStatsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
     */
    public com.github.paohaijiao.proto.JQuickPhysicalStatsProto.Builder getExecutionStatsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getExecutionStatsFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
     */
    public com.github.paohaijiao.proto.JQuickPhysicalStatsProtoOrBuilder getExecutionStatsOrBuilder() {
      if (executionStatsBuilder_ != null) {
        return executionStatsBuilder_.getMessageOrBuilder();
      } else {
        return executionStats_ == null ?
            com.github.paohaijiao.proto.JQuickPhysicalStatsProto.getDefaultInstance() : executionStats_;
      }
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.paohaijiao.proto.JQuickPhysicalStatsProto, com.github.paohaijiao.proto.JQuickPhysicalStatsProto.Builder, com.github.paohaijiao.proto.JQuickPhysicalStatsProtoOrBuilder> 
        getExecutionStatsFieldBuilder() {
      if (executionStatsBuilder_ == null) {
        executionStatsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.paohaijiao.proto.JQuickPhysicalStatsProto, com.github.paohaijiao.proto.JQuickPhysicalStatsProto.Builder, com.github.paohaijiao.proto.JQuickPhysicalStatsProtoOrBuilder>(
                getExecutionStats(),
                getParentForChildren(),
                isClean());
        executionStats_ = null;
      }
      return executionStatsBuilder_;
    }

    private long processedRows_ ;
    /**
     * <code>int64 processed_rows = 6;</code>
     * @return The processedRows.
     */
    @java.lang.Override
    public long getProcessedRows() {
      return processedRows_;
    }
    /**
     * <code>int64 processed_rows = 6;</code>
     * @param value The processedRows to set.
     * @return This builder for chaining.
     */
    public Builder setProcessedRows(long value) {
      
      processedRows_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 processed_rows = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessedRows() {
      bitField0_ = (bitField0_ & ~0x00000020);
      processedRows_ = 0L;
      onChanged();
      return this;
    }

    private long executionTimeMs_ ;
    /**
     * <code>int64 execution_time_ms = 7;</code>
     * @return The executionTimeMs.
     */
    @java.lang.Override
    public long getExecutionTimeMs() {
      return executionTimeMs_;
    }
    /**
     * <code>int64 execution_time_ms = 7;</code>
     * @param value The executionTimeMs to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionTimeMs(long value) {
      
      executionTimeMs_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 execution_time_ms = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutionTimeMs() {
      bitField0_ = (bitField0_ & ~0x00000040);
      executionTimeMs_ = 0L;
      onChanged();
      return this;
    }

    private long memoryUsedBytes_ ;
    /**
     * <pre>
     * 实际使用的内存
     * </pre>
     *
     * <code>int64 memory_used_bytes = 8;</code>
     * @return The memoryUsedBytes.
     */
    @java.lang.Override
    public long getMemoryUsedBytes() {
      return memoryUsedBytes_;
    }
    /**
     * <pre>
     * 实际使用的内存
     * </pre>
     *
     * <code>int64 memory_used_bytes = 8;</code>
     * @param value The memoryUsedBytes to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryUsedBytes(long value) {
      
      memoryUsedBytes_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 实际使用的内存
     * </pre>
     *
     * <code>int64 memory_used_bytes = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryUsedBytes() {
      bitField0_ = (bitField0_ & ~0x00000080);
      memoryUsedBytes_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> taskMetrics_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetTaskMetrics() {
      if (taskMetrics_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TaskMetricsDefaultEntryHolder.defaultEntry);
      }
      return taskMetrics_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableTaskMetrics() {
      if (taskMetrics_ == null) {
        taskMetrics_ = com.google.protobuf.MapField.newMapField(
            TaskMetricsDefaultEntryHolder.defaultEntry);
      }
      if (!taskMetrics_.isMutable()) {
        taskMetrics_ = taskMetrics_.copy();
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return taskMetrics_;
    }
    public int getTaskMetricsCount() {
      return internalGetTaskMetrics().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; task_metrics = 9;</code>
     */
    @java.lang.Override
    public boolean containsTaskMetrics(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTaskMetrics().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTaskMetricsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTaskMetrics() {
      return getTaskMetricsMap();
    }
    /**
     * <code>map&lt;string, string&gt; task_metrics = 9;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getTaskMetricsMap() {
      return internalGetTaskMetrics().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; task_metrics = 9;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getTaskMetricsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTaskMetrics().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; task_metrics = 9;</code>
     */
    @java.lang.Override
    public java.lang.String getTaskMetricsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTaskMetrics().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearTaskMetrics() {
      bitField0_ = (bitField0_ & ~0x00000100);
      internalGetMutableTaskMetrics().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; task_metrics = 9;</code>
     */
    public Builder removeTaskMetrics(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTaskMetrics().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableTaskMetrics() {
      bitField0_ |= 0x00000100;
      return internalGetMutableTaskMetrics().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; task_metrics = 9;</code>
     */
    public Builder putTaskMetrics(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableTaskMetrics().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; task_metrics = 9;</code>
     */
    public Builder putAllTaskMetrics(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTaskMetrics().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000100;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.paohaijiao.proto.JQuickExecuteTaskResponse)
  }

  // @@protoc_insertion_point(class_scope:com.github.paohaijiao.proto.JQuickExecuteTaskResponse)
  private static final com.github.paohaijiao.proto.JQuickExecuteTaskResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.paohaijiao.proto.JQuickExecuteTaskResponse();
  }

  public static com.github.paohaijiao.proto.JQuickExecuteTaskResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JQuickExecuteTaskResponse>
      PARSER = new com.google.protobuf.AbstractParser<JQuickExecuteTaskResponse>() {
    @java.lang.Override
    public JQuickExecuteTaskResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JQuickExecuteTaskResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JQuickExecuteTaskResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickExecuteTaskResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

