// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

/**
 * <pre>
 * 内存表分区信息
 * </pre>
 *
 * Protobuf type {@code com.github.paohaijiao.proto.JQuickTablePartitionInfoProto}
 */
public final class JQuickTablePartitionInfoProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.paohaijiao.proto.JQuickTablePartitionInfoProto)
    JQuickTablePartitionInfoProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JQuickTablePartitionInfoProto.newBuilder() to construct.
  private JQuickTablePartitionInfoProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JQuickTablePartitionInfoProto() {
    tableName_ = "";
    partitionColumn_ = "";
    strategy_ = 0;
    partitions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JQuickTablePartitionInfoProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTablePartitionInfoProto_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetWorkerPartitionMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTablePartitionInfoProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.paohaijiao.proto.JQuickTablePartitionInfoProto.class, com.github.paohaijiao.proto.JQuickTablePartitionInfoProto.Builder.class);
  }

  public static final int TABLE_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tableName_ = "";
  /**
   * <code>string table_name = 1;</code>
   * @return The tableName.
   */
  @java.lang.Override
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <code>string table_name = 1;</code>
   * @return The bytes for tableName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTITION_COLUMN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object partitionColumn_ = "";
  /**
   * <code>string partition_column = 2;</code>
   * @return The partitionColumn.
   */
  @java.lang.Override
  public java.lang.String getPartitionColumn() {
    java.lang.Object ref = partitionColumn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partitionColumn_ = s;
      return s;
    }
  }
  /**
   * <code>string partition_column = 2;</code>
   * @return The bytes for partitionColumn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPartitionColumnBytes() {
    java.lang.Object ref = partitionColumn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partitionColumn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRATEGY_FIELD_NUMBER = 3;
  private int strategy_ = 0;
  /**
   * <code>.com.github.paohaijiao.proto.JQuickPartitionStrategyProto strategy = 3;</code>
   * @return The enum numeric value on the wire for strategy.
   */
  @java.lang.Override public int getStrategyValue() {
    return strategy_;
  }
  /**
   * <code>.com.github.paohaijiao.proto.JQuickPartitionStrategyProto strategy = 3;</code>
   * @return The strategy.
   */
  @java.lang.Override public com.github.paohaijiao.proto.JQuickPartitionStrategyProto getStrategy() {
    com.github.paohaijiao.proto.JQuickPartitionStrategyProto result = com.github.paohaijiao.proto.JQuickPartitionStrategyProto.forNumber(strategy_);
    return result == null ? com.github.paohaijiao.proto.JQuickPartitionStrategyProto.UNRECOGNIZED : result;
  }

  public static final int PARTITION_COUNT_FIELD_NUMBER = 4;
  private int partitionCount_ = 0;
  /**
   * <code>int32 partition_count = 4;</code>
   * @return The partitionCount.
   */
  @java.lang.Override
  public int getPartitionCount() {
    return partitionCount_;
  }

  public static final int PARTITIONS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.github.paohaijiao.proto.JQuickMemoryPartitionProto> partitions_;
  /**
   * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.paohaijiao.proto.JQuickMemoryPartitionProto> getPartitionsList() {
    return partitions_;
  }
  /**
   * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.paohaijiao.proto.JQuickMemoryPartitionProtoOrBuilder> 
      getPartitionsOrBuilderList() {
    return partitions_;
  }
  /**
   * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
   */
  @java.lang.Override
  public int getPartitionsCount() {
    return partitions_.size();
  }
  /**
   * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
   */
  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickMemoryPartitionProto getPartitions(int index) {
    return partitions_.get(index);
  }
  /**
   * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
   */
  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickMemoryPartitionProtoOrBuilder getPartitionsOrBuilder(
      int index) {
    return partitions_.get(index);
  }

  public static final int WORKER_PARTITION_MAP_FIELD_NUMBER = 6;
  private static final class WorkerPartitionMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTablePartitionInfoProto_WorkerPartitionMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> workerPartitionMap_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetWorkerPartitionMap() {
    if (workerPartitionMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          WorkerPartitionMapDefaultEntryHolder.defaultEntry);
    }
    return workerPartitionMap_;
  }
  public int getWorkerPartitionMapCount() {
    return internalGetWorkerPartitionMap().getMap().size();
  }
  /**
   * <pre>
   * 内存分布信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
   */
  @java.lang.Override
  public boolean containsWorkerPartitionMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetWorkerPartitionMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getWorkerPartitionMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getWorkerPartitionMap() {
    return getWorkerPartitionMapMap();
  }
  /**
   * <pre>
   * 内存分布信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getWorkerPartitionMapMap() {
    return internalGetWorkerPartitionMap().getMap();
  }
  /**
   * <pre>
   * 内存分布信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getWorkerPartitionMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetWorkerPartitionMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 内存分布信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
   */
  @java.lang.Override
  public java.lang.String getWorkerPartitionMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetWorkerPartitionMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int IS_MEMORY_RESIDENT_FIELD_NUMBER = 7;
  private boolean isMemoryResident_ = false;
  /**
   * <pre>
   * 是否常驻内存
   * </pre>
   *
   * <code>bool is_memory_resident = 7;</code>
   * @return The isMemoryResident.
   */
  @java.lang.Override
  public boolean getIsMemoryResident() {
    return isMemoryResident_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tableName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partitionColumn_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, partitionColumn_);
    }
    if (strategy_ != com.github.paohaijiao.proto.JQuickPartitionStrategyProto.PARTITION_HASH.getNumber()) {
      output.writeEnum(3, strategy_);
    }
    if (partitionCount_ != 0) {
      output.writeInt32(4, partitionCount_);
    }
    for (int i = 0; i < partitions_.size(); i++) {
      output.writeMessage(5, partitions_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetWorkerPartitionMap(),
        WorkerPartitionMapDefaultEntryHolder.defaultEntry,
        6);
    if (isMemoryResident_ != false) {
      output.writeBool(7, isMemoryResident_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tableName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partitionColumn_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, partitionColumn_);
    }
    if (strategy_ != com.github.paohaijiao.proto.JQuickPartitionStrategyProto.PARTITION_HASH.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, strategy_);
    }
    if (partitionCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, partitionCount_);
    }
    for (int i = 0; i < partitions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, partitions_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetWorkerPartitionMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      workerPartitionMap__ = WorkerPartitionMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, workerPartitionMap__);
    }
    if (isMemoryResident_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, isMemoryResident_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.paohaijiao.proto.JQuickTablePartitionInfoProto)) {
      return super.equals(obj);
    }
    com.github.paohaijiao.proto.JQuickTablePartitionInfoProto other = (com.github.paohaijiao.proto.JQuickTablePartitionInfoProto) obj;

    if (!getTableName()
        .equals(other.getTableName())) return false;
    if (!getPartitionColumn()
        .equals(other.getPartitionColumn())) return false;
    if (strategy_ != other.strategy_) return false;
    if (getPartitionCount()
        != other.getPartitionCount()) return false;
    if (!getPartitionsList()
        .equals(other.getPartitionsList())) return false;
    if (!internalGetWorkerPartitionMap().equals(
        other.internalGetWorkerPartitionMap())) return false;
    if (getIsMemoryResident()
        != other.getIsMemoryResident()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    hash = (37 * hash) + PARTITION_COLUMN_FIELD_NUMBER;
    hash = (53 * hash) + getPartitionColumn().hashCode();
    hash = (37 * hash) + STRATEGY_FIELD_NUMBER;
    hash = (53 * hash) + strategy_;
    hash = (37 * hash) + PARTITION_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPartitionCount();
    if (getPartitionsCount() > 0) {
      hash = (37 * hash) + PARTITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPartitionsList().hashCode();
    }
    if (!internalGetWorkerPartitionMap().getMap().isEmpty()) {
      hash = (37 * hash) + WORKER_PARTITION_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetWorkerPartitionMap().hashCode();
    }
    hash = (37 * hash) + IS_MEMORY_RESIDENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsMemoryResident());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.paohaijiao.proto.JQuickTablePartitionInfoProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 内存表分区信息
   * </pre>
   *
   * Protobuf type {@code com.github.paohaijiao.proto.JQuickTablePartitionInfoProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.paohaijiao.proto.JQuickTablePartitionInfoProto)
      com.github.paohaijiao.proto.JQuickTablePartitionInfoProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTablePartitionInfoProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetWorkerPartitionMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableWorkerPartitionMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTablePartitionInfoProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.paohaijiao.proto.JQuickTablePartitionInfoProto.class, com.github.paohaijiao.proto.JQuickTablePartitionInfoProto.Builder.class);
    }

    // Construct using com.github.paohaijiao.proto.JQuickTablePartitionInfoProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tableName_ = "";
      partitionColumn_ = "";
      strategy_ = 0;
      partitionCount_ = 0;
      if (partitionsBuilder_ == null) {
        partitions_ = java.util.Collections.emptyList();
      } else {
        partitions_ = null;
        partitionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      internalGetMutableWorkerPartitionMap().clear();
      isMemoryResident_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTablePartitionInfoProto_descriptor;
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickTablePartitionInfoProto getDefaultInstanceForType() {
      return com.github.paohaijiao.proto.JQuickTablePartitionInfoProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickTablePartitionInfoProto build() {
      com.github.paohaijiao.proto.JQuickTablePartitionInfoProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickTablePartitionInfoProto buildPartial() {
      com.github.paohaijiao.proto.JQuickTablePartitionInfoProto result = new com.github.paohaijiao.proto.JQuickTablePartitionInfoProto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.github.paohaijiao.proto.JQuickTablePartitionInfoProto result) {
      if (partitionsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          partitions_ = java.util.Collections.unmodifiableList(partitions_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.partitions_ = partitions_;
      } else {
        result.partitions_ = partitionsBuilder_.build();
      }
    }

    private void buildPartial0(com.github.paohaijiao.proto.JQuickTablePartitionInfoProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tableName_ = tableName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.partitionColumn_ = partitionColumn_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.strategy_ = strategy_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.partitionCount_ = partitionCount_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.workerPartitionMap_ = internalGetWorkerPartitionMap();
        result.workerPartitionMap_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.isMemoryResident_ = isMemoryResident_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.paohaijiao.proto.JQuickTablePartitionInfoProto) {
        return mergeFrom((com.github.paohaijiao.proto.JQuickTablePartitionInfoProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.paohaijiao.proto.JQuickTablePartitionInfoProto other) {
      if (other == com.github.paohaijiao.proto.JQuickTablePartitionInfoProto.getDefaultInstance()) return this;
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPartitionColumn().isEmpty()) {
        partitionColumn_ = other.partitionColumn_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.strategy_ != 0) {
        setStrategyValue(other.getStrategyValue());
      }
      if (other.getPartitionCount() != 0) {
        setPartitionCount(other.getPartitionCount());
      }
      if (partitionsBuilder_ == null) {
        if (!other.partitions_.isEmpty()) {
          if (partitions_.isEmpty()) {
            partitions_ = other.partitions_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePartitionsIsMutable();
            partitions_.addAll(other.partitions_);
          }
          onChanged();
        }
      } else {
        if (!other.partitions_.isEmpty()) {
          if (partitionsBuilder_.isEmpty()) {
            partitionsBuilder_.dispose();
            partitionsBuilder_ = null;
            partitions_ = other.partitions_;
            bitField0_ = (bitField0_ & ~0x00000010);
            partitionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPartitionsFieldBuilder() : null;
          } else {
            partitionsBuilder_.addAllMessages(other.partitions_);
          }
        }
      }
      internalGetMutableWorkerPartitionMap().mergeFrom(
          other.internalGetWorkerPartitionMap());
      bitField0_ |= 0x00000020;
      if (other.getIsMemoryResident() != false) {
        setIsMemoryResident(other.getIsMemoryResident());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tableName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              partitionColumn_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              strategy_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              partitionCount_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              com.github.paohaijiao.proto.JQuickMemoryPartitionProto m =
                  input.readMessage(
                      com.github.paohaijiao.proto.JQuickMemoryPartitionProto.parser(),
                      extensionRegistry);
              if (partitionsBuilder_ == null) {
                ensurePartitionsIsMutable();
                partitions_.add(m);
              } else {
                partitionsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              workerPartitionMap__ = input.readMessage(
                  WorkerPartitionMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableWorkerPartitionMap().getMutableMap().put(
                  workerPartitionMap__.getKey(), workerPartitionMap__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              isMemoryResident_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tableName_ = "";
    /**
     * <code>string table_name = 1;</code>
     * @return The tableName.
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string table_name = 1;</code>
     * @return The bytes for tableName.
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string table_name = 1;</code>
     * @param value The tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tableName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string table_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableName() {
      tableName_ = getDefaultInstance().getTableName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string table_name = 1;</code>
     * @param value The bytes for tableName to set.
     * @return This builder for chaining.
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tableName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object partitionColumn_ = "";
    /**
     * <code>string partition_column = 2;</code>
     * @return The partitionColumn.
     */
    public java.lang.String getPartitionColumn() {
      java.lang.Object ref = partitionColumn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partitionColumn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string partition_column = 2;</code>
     * @return The bytes for partitionColumn.
     */
    public com.google.protobuf.ByteString
        getPartitionColumnBytes() {
      java.lang.Object ref = partitionColumn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partitionColumn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string partition_column = 2;</code>
     * @param value The partitionColumn to set.
     * @return This builder for chaining.
     */
    public Builder setPartitionColumn(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      partitionColumn_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string partition_column = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartitionColumn() {
      partitionColumn_ = getDefaultInstance().getPartitionColumn();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string partition_column = 2;</code>
     * @param value The bytes for partitionColumn to set.
     * @return This builder for chaining.
     */
    public Builder setPartitionColumnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      partitionColumn_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int strategy_ = 0;
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPartitionStrategyProto strategy = 3;</code>
     * @return The enum numeric value on the wire for strategy.
     */
    @java.lang.Override public int getStrategyValue() {
      return strategy_;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPartitionStrategyProto strategy = 3;</code>
     * @param value The enum numeric value on the wire for strategy to set.
     * @return This builder for chaining.
     */
    public Builder setStrategyValue(int value) {
      strategy_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPartitionStrategyProto strategy = 3;</code>
     * @return The strategy.
     */
    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickPartitionStrategyProto getStrategy() {
      com.github.paohaijiao.proto.JQuickPartitionStrategyProto result = com.github.paohaijiao.proto.JQuickPartitionStrategyProto.forNumber(strategy_);
      return result == null ? com.github.paohaijiao.proto.JQuickPartitionStrategyProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPartitionStrategyProto strategy = 3;</code>
     * @param value The strategy to set.
     * @return This builder for chaining.
     */
    public Builder setStrategy(com.github.paohaijiao.proto.JQuickPartitionStrategyProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      strategy_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickPartitionStrategyProto strategy = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStrategy() {
      bitField0_ = (bitField0_ & ~0x00000004);
      strategy_ = 0;
      onChanged();
      return this;
    }

    private int partitionCount_ ;
    /**
     * <code>int32 partition_count = 4;</code>
     * @return The partitionCount.
     */
    @java.lang.Override
    public int getPartitionCount() {
      return partitionCount_;
    }
    /**
     * <code>int32 partition_count = 4;</code>
     * @param value The partitionCount to set.
     * @return This builder for chaining.
     */
    public Builder setPartitionCount(int value) {
      
      partitionCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 partition_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartitionCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      partitionCount_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.github.paohaijiao.proto.JQuickMemoryPartitionProto> partitions_ =
      java.util.Collections.emptyList();
    private void ensurePartitionsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        partitions_ = new java.util.ArrayList<com.github.paohaijiao.proto.JQuickMemoryPartitionProto>(partitions_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.paohaijiao.proto.JQuickMemoryPartitionProto, com.github.paohaijiao.proto.JQuickMemoryPartitionProto.Builder, com.github.paohaijiao.proto.JQuickMemoryPartitionProtoOrBuilder> partitionsBuilder_;

    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public java.util.List<com.github.paohaijiao.proto.JQuickMemoryPartitionProto> getPartitionsList() {
      if (partitionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(partitions_);
      } else {
        return partitionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public int getPartitionsCount() {
      if (partitionsBuilder_ == null) {
        return partitions_.size();
      } else {
        return partitionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public com.github.paohaijiao.proto.JQuickMemoryPartitionProto getPartitions(int index) {
      if (partitionsBuilder_ == null) {
        return partitions_.get(index);
      } else {
        return partitionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public Builder setPartitions(
        int index, com.github.paohaijiao.proto.JQuickMemoryPartitionProto value) {
      if (partitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionsIsMutable();
        partitions_.set(index, value);
        onChanged();
      } else {
        partitionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public Builder setPartitions(
        int index, com.github.paohaijiao.proto.JQuickMemoryPartitionProto.Builder builderForValue) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.set(index, builderForValue.build());
        onChanged();
      } else {
        partitionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public Builder addPartitions(com.github.paohaijiao.proto.JQuickMemoryPartitionProto value) {
      if (partitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionsIsMutable();
        partitions_.add(value);
        onChanged();
      } else {
        partitionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public Builder addPartitions(
        int index, com.github.paohaijiao.proto.JQuickMemoryPartitionProto value) {
      if (partitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionsIsMutable();
        partitions_.add(index, value);
        onChanged();
      } else {
        partitionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public Builder addPartitions(
        com.github.paohaijiao.proto.JQuickMemoryPartitionProto.Builder builderForValue) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.add(builderForValue.build());
        onChanged();
      } else {
        partitionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public Builder addPartitions(
        int index, com.github.paohaijiao.proto.JQuickMemoryPartitionProto.Builder builderForValue) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.add(index, builderForValue.build());
        onChanged();
      } else {
        partitionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public Builder addAllPartitions(
        java.lang.Iterable<? extends com.github.paohaijiao.proto.JQuickMemoryPartitionProto> values) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, partitions_);
        onChanged();
      } else {
        partitionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public Builder clearPartitions() {
      if (partitionsBuilder_ == null) {
        partitions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        partitionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public Builder removePartitions(int index) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.remove(index);
        onChanged();
      } else {
        partitionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public com.github.paohaijiao.proto.JQuickMemoryPartitionProto.Builder getPartitionsBuilder(
        int index) {
      return getPartitionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public com.github.paohaijiao.proto.JQuickMemoryPartitionProtoOrBuilder getPartitionsOrBuilder(
        int index) {
      if (partitionsBuilder_ == null) {
        return partitions_.get(index);  } else {
        return partitionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public java.util.List<? extends com.github.paohaijiao.proto.JQuickMemoryPartitionProtoOrBuilder> 
         getPartitionsOrBuilderList() {
      if (partitionsBuilder_ != null) {
        return partitionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(partitions_);
      }
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public com.github.paohaijiao.proto.JQuickMemoryPartitionProto.Builder addPartitionsBuilder() {
      return getPartitionsFieldBuilder().addBuilder(
          com.github.paohaijiao.proto.JQuickMemoryPartitionProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public com.github.paohaijiao.proto.JQuickMemoryPartitionProto.Builder addPartitionsBuilder(
        int index) {
      return getPartitionsFieldBuilder().addBuilder(
          index, com.github.paohaijiao.proto.JQuickMemoryPartitionProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.github.paohaijiao.proto.JQuickMemoryPartitionProto partitions = 5;</code>
     */
    public java.util.List<com.github.paohaijiao.proto.JQuickMemoryPartitionProto.Builder> 
         getPartitionsBuilderList() {
      return getPartitionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.paohaijiao.proto.JQuickMemoryPartitionProto, com.github.paohaijiao.proto.JQuickMemoryPartitionProto.Builder, com.github.paohaijiao.proto.JQuickMemoryPartitionProtoOrBuilder> 
        getPartitionsFieldBuilder() {
      if (partitionsBuilder_ == null) {
        partitionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.paohaijiao.proto.JQuickMemoryPartitionProto, com.github.paohaijiao.proto.JQuickMemoryPartitionProto.Builder, com.github.paohaijiao.proto.JQuickMemoryPartitionProtoOrBuilder>(
                partitions_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        partitions_ = null;
      }
      return partitionsBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> workerPartitionMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetWorkerPartitionMap() {
      if (workerPartitionMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            WorkerPartitionMapDefaultEntryHolder.defaultEntry);
      }
      return workerPartitionMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableWorkerPartitionMap() {
      if (workerPartitionMap_ == null) {
        workerPartitionMap_ = com.google.protobuf.MapField.newMapField(
            WorkerPartitionMapDefaultEntryHolder.defaultEntry);
      }
      if (!workerPartitionMap_.isMutable()) {
        workerPartitionMap_ = workerPartitionMap_.copy();
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return workerPartitionMap_;
    }
    public int getWorkerPartitionMapCount() {
      return internalGetWorkerPartitionMap().getMap().size();
    }
    /**
     * <pre>
     * 内存分布信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
     */
    @java.lang.Override
    public boolean containsWorkerPartitionMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetWorkerPartitionMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getWorkerPartitionMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getWorkerPartitionMap() {
      return getWorkerPartitionMapMap();
    }
    /**
     * <pre>
     * 内存分布信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getWorkerPartitionMapMap() {
      return internalGetWorkerPartitionMap().getMap();
    }
    /**
     * <pre>
     * 内存分布信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getWorkerPartitionMapOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetWorkerPartitionMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 内存分布信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
     */
    @java.lang.Override
    public java.lang.String getWorkerPartitionMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetWorkerPartitionMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearWorkerPartitionMap() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableWorkerPartitionMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 内存分布信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
     */
    public Builder removeWorkerPartitionMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableWorkerPartitionMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableWorkerPartitionMap() {
      bitField0_ |= 0x00000020;
      return internalGetMutableWorkerPartitionMap().getMutableMap();
    }
    /**
     * <pre>
     * 内存分布信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
     */
    public Builder putWorkerPartitionMap(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableWorkerPartitionMap().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * 内存分布信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; worker_partition_map = 6;</code>
     */
    public Builder putAllWorkerPartitionMap(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableWorkerPartitionMap().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }

    private boolean isMemoryResident_ ;
    /**
     * <pre>
     * 是否常驻内存
     * </pre>
     *
     * <code>bool is_memory_resident = 7;</code>
     * @return The isMemoryResident.
     */
    @java.lang.Override
    public boolean getIsMemoryResident() {
      return isMemoryResident_;
    }
    /**
     * <pre>
     * 是否常驻内存
     * </pre>
     *
     * <code>bool is_memory_resident = 7;</code>
     * @param value The isMemoryResident to set.
     * @return This builder for chaining.
     */
    public Builder setIsMemoryResident(boolean value) {
      
      isMemoryResident_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否常驻内存
     * </pre>
     *
     * <code>bool is_memory_resident = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsMemoryResident() {
      bitField0_ = (bitField0_ & ~0x00000040);
      isMemoryResident_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.paohaijiao.proto.JQuickTablePartitionInfoProto)
  }

  // @@protoc_insertion_point(class_scope:com.github.paohaijiao.proto.JQuickTablePartitionInfoProto)
  private static final com.github.paohaijiao.proto.JQuickTablePartitionInfoProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.paohaijiao.proto.JQuickTablePartitionInfoProto();
  }

  public static com.github.paohaijiao.proto.JQuickTablePartitionInfoProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JQuickTablePartitionInfoProto>
      PARSER = new com.google.protobuf.AbstractParser<JQuickTablePartitionInfoProto>() {
    @java.lang.Override
    public JQuickTablePartitionInfoProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JQuickTablePartitionInfoProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JQuickTablePartitionInfoProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickTablePartitionInfoProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

