// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

public interface ExecuteTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.paohaijiao.proto.ExecuteTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>.com.github.paohaijiao.proto.ExecuteTaskResponse.TaskStatus status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.github.paohaijiao.proto.ExecuteTaskResponse.TaskStatus status = 2;</code>
   * @return The status.
   */
  ExecuteTaskResponse.TaskStatus getStatus();

  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
   * @return Whether the resultData field is set.
   */
  boolean hasResultData();
  /**
   * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
   * @return The resultData.
   */
  JQuickDataSetProto getResultData();
  /**
   * <code>.com.github.paohaijiao.proto.JQuickDataSetProto result_data = 4;</code>
   */
  JQuickDataSetProtoOrBuilder getResultDataOrBuilder();

  /**
   * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
   * @return Whether the executionStats field is set.
   */
  boolean hasExecutionStats();
  /**
   * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
   * @return The executionStats.
   */
  JQuickPhysicalStatsProto getExecutionStats();
  /**
   * <code>.com.github.paohaijiao.proto.JQuickPhysicalStatsProto execution_stats = 5;</code>
   */
  JQuickPhysicalStatsProtoOrBuilder getExecutionStatsOrBuilder();

  /**
   * <code>int64 processed_rows = 6;</code>
   * @return The processedRows.
   */
  long getProcessedRows();

  /**
   * <code>int64 execution_time_ms = 7;</code>
   * @return The executionTimeMs.
   */
  long getExecutionTimeMs();
}
