// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

public interface JQuickSubmitQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.paohaijiao.proto.JQuickSubmitQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query_id = 1;</code>
   * @return The queryId.
   */
  java.lang.String getQueryId();
  /**
   * <code>string query_id = 1;</code>
   * @return The bytes for queryId.
   */
  com.google.protobuf.ByteString
      getQueryIdBytes();

  /**
   * <code>string sql = 2;</code>
   * @return The sql.
   */
  java.lang.String getSql();
  /**
   * <code>string sql = 2;</code>
   * @return The bytes for sql.
   */
  com.google.protobuf.ByteString
      getSqlBytes();

  /**
   * <code>map&lt;string, string&gt; parameters = 3;</code>
   */
  int getParametersCount();
  /**
   * <code>map&lt;string, string&gt; parameters = 3;</code>
   */
  boolean containsParameters(
      java.lang.String key);
  /**
   * Use {@link #getParametersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getParameters();
  /**
   * <code>map&lt;string, string&gt; parameters = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getParametersMap();
  /**
   * <code>map&lt;string, string&gt; parameters = 3;</code>
   */
  /* nullable */
java.lang.String getParametersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; parameters = 3;</code>
   */
  java.lang.String getParametersOrThrow(
      java.lang.String key);

  /**
   * <code>int32 default_parallelism = 4;</code>
   * @return The defaultParallelism.
   */
  int getDefaultParallelism();

  /**
   * <code>.com.github.paohaijiao.proto.JQuickQueryOptionsProto options = 5;</code>
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <code>.com.github.paohaijiao.proto.JQuickQueryOptionsProto options = 5;</code>
   * @return The options.
   */
  com.github.paohaijiao.proto.JQuickQueryOptionsProto getOptions();
  /**
   * <code>.com.github.paohaijiao.proto.JQuickQueryOptionsProto options = 5;</code>
   */
  com.github.paohaijiao.proto.JQuickQueryOptionsProtoOrBuilder getOptionsOrBuilder();
}
