// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

public interface JQuickMemoryPartitionProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.paohaijiao.proto.JQuickMemoryPartitionProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string partition_id = 1;</code>
   * @return The partitionId.
   */
  java.lang.String getPartitionId();
  /**
   * <code>string partition_id = 1;</code>
   * @return The bytes for partitionId.
   */
  com.google.protobuf.ByteString
      getPartitionIdBytes();

  /**
   * <code>int32 partition_index = 2;</code>
   * @return The partitionIndex.
   */
  int getPartitionIndex();

  /**
   * <code>int32 total_partitions = 3;</code>
   * @return The totalPartitions.
   */
  int getTotalPartitions();

  /**
   * <pre>
   * 目标Worker ID
   * </pre>
   *
   * <code>string target_worker_id = 4;</code>
   * @return The targetWorkerId.
   */
  java.lang.String getTargetWorkerId();
  /**
   * <pre>
   * 目标Worker ID
   * </pre>
   *
   * <code>string target_worker_id = 4;</code>
   * @return The bytes for targetWorkerId.
   */
  com.google.protobuf.ByteString
      getTargetWorkerIdBytes();

  /**
   * <pre>
   * 目标Worker主机
   * </pre>
   *
   * <code>string target_host = 5;</code>
   * @return The targetHost.
   */
  java.lang.String getTargetHost();
  /**
   * <pre>
   * 目标Worker主机
   * </pre>
   *
   * <code>string target_host = 5;</code>
   * @return The bytes for targetHost.
   */
  com.google.protobuf.ByteString
      getTargetHostBytes();

  /**
   * <pre>
   * 目标Worker端口
   * </pre>
   *
   * <code>int32 target_port = 6;</code>
   * @return The targetPort.
   */
  int getTargetPort();

  /**
   * <pre>
   * 内存数据（直接传输，不经过外部存储）
   * </pre>
   *
   * <code>.com.github.paohaijiao.proto.JQuickDataSetProto data = 7;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <pre>
   * 内存数据（直接传输，不经过外部存储）
   * </pre>
   *
   * <code>.com.github.paohaijiao.proto.JQuickDataSetProto data = 7;</code>
   * @return The data.
   */
  com.github.paohaijiao.proto.JQuickDataSetProto getData();
  /**
   * <pre>
   * 内存数据（直接传输，不经过外部存储）
   * </pre>
   *
   * <code>.com.github.paohaijiao.proto.JQuickDataSetProto data = 7;</code>
   */
  com.github.paohaijiao.proto.JQuickDataSetProtoOrBuilder getDataOrBuilder();

  /**
   * <pre>
   * 分区键信息（用于路由）
   * </pre>
   *
   * <code>repeated string partition_key_names = 8;</code>
   * @return A list containing the partitionKeyNames.
   */
  java.util.List<java.lang.String>
      getPartitionKeyNamesList();
  /**
   * <pre>
   * 分区键信息（用于路由）
   * </pre>
   *
   * <code>repeated string partition_key_names = 8;</code>
   * @return The count of partitionKeyNames.
   */
  int getPartitionKeyNamesCount();
  /**
   * <pre>
   * 分区键信息（用于路由）
   * </pre>
   *
   * <code>repeated string partition_key_names = 8;</code>
   * @param index The index of the element to return.
   * @return The partitionKeyNames at the given index.
   */
  java.lang.String getPartitionKeyNames(int index);
  /**
   * <pre>
   * 分区键信息（用于路由）
   * </pre>
   *
   * <code>repeated string partition_key_names = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the partitionKeyNames at the given index.
   */
  com.google.protobuf.ByteString
      getPartitionKeyNamesBytes(int index);

  /**
   * <pre>
   * 哈希值范围
   * </pre>
   *
   * <code>bytes partition_key_hash = 9;</code>
   * @return The partitionKeyHash.
   */
  com.google.protobuf.ByteString getPartitionKeyHash();

  /**
   * <pre>
   * 流式传输标记
   * </pre>
   *
   * <code>bool is_streaming = 10;</code>
   * @return The isStreaming.
   */
  boolean getIsStreaming();

  /**
   * <code>int64 estimated_size = 11;</code>
   * @return The estimatedSize.
   */
  long getEstimatedSize();
}
