// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

public interface JQuickTopNNodeProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.paohaijiao.proto.JQuickTopNNodeProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.github.paohaijiao.proto.JQuickSortNodeProto.OrderByItemProto order_by_items = 1;</code>
   */
  java.util.List<com.github.paohaijiao.proto.JQuickSortNodeProto.OrderByItemProto> 
      getOrderByItemsList();
  /**
   * <code>repeated .com.github.paohaijiao.proto.JQuickSortNodeProto.OrderByItemProto order_by_items = 1;</code>
   */
  com.github.paohaijiao.proto.JQuickSortNodeProto.OrderByItemProto getOrderByItems(int index);
  /**
   * <code>repeated .com.github.paohaijiao.proto.JQuickSortNodeProto.OrderByItemProto order_by_items = 1;</code>
   */
  int getOrderByItemsCount();
  /**
   * <code>repeated .com.github.paohaijiao.proto.JQuickSortNodeProto.OrderByItemProto order_by_items = 1;</code>
   */
  java.util.List<? extends com.github.paohaijiao.proto.JQuickSortNodeProto.OrderByItemProtoOrBuilder> 
      getOrderByItemsOrBuilderList();
  /**
   * <code>repeated .com.github.paohaijiao.proto.JQuickSortNodeProto.OrderByItemProto order_by_items = 1;</code>
   */
  com.github.paohaijiao.proto.JQuickSortNodeProto.OrderByItemProtoOrBuilder getOrderByItemsOrBuilder(
      int index);

  /**
   * <code>int32 limit = 2;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>int32 offset = 3;</code>
   * @return The offset.
   */
  int getOffset();
}
