// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

/**
 * Protobuf enum {@code com.github.paohaijiao.proto.JQuickJoinDistributionProto}
 */
public enum JQuickJoinDistributionProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 本地连接（数据已经在同一节点）
   * </pre>
   *
   * <code>JOIN_DIST_LOCAL = 0;</code>
   */
  JOIN_DIST_LOCAL(0),
  /**
   * <pre>
   * 动态Shuffle重分布
   * </pre>
   *
   * <code>JOIN_DIST_SHUFFLE = 1;</code>
   */
  JOIN_DIST_SHUFFLE(1),
  /**
   * <pre>
   * 广播小表到所有节点
   * </pre>
   *
   * <code>JOIN_DIST_BROADCAST = 2;</code>
   */
  JOIN_DIST_BROADCAST(2),
  /**
   * <pre>
   * 基于分区键连接
   * </pre>
   *
   * <code>JOIN_DIST_PARTITIONED = 3;</code>
   */
  JOIN_DIST_PARTITIONED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 本地连接（数据已经在同一节点）
   * </pre>
   *
   * <code>JOIN_DIST_LOCAL = 0;</code>
   */
  public static final int JOIN_DIST_LOCAL_VALUE = 0;
  /**
   * <pre>
   * 动态Shuffle重分布
   * </pre>
   *
   * <code>JOIN_DIST_SHUFFLE = 1;</code>
   */
  public static final int JOIN_DIST_SHUFFLE_VALUE = 1;
  /**
   * <pre>
   * 广播小表到所有节点
   * </pre>
   *
   * <code>JOIN_DIST_BROADCAST = 2;</code>
   */
  public static final int JOIN_DIST_BROADCAST_VALUE = 2;
  /**
   * <pre>
   * 基于分区键连接
   * </pre>
   *
   * <code>JOIN_DIST_PARTITIONED = 3;</code>
   */
  public static final int JOIN_DIST_PARTITIONED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static JQuickJoinDistributionProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static JQuickJoinDistributionProto forNumber(int value) {
    switch (value) {
      case 0: return JOIN_DIST_LOCAL;
      case 1: return JOIN_DIST_SHUFFLE;
      case 2: return JOIN_DIST_BROADCAST;
      case 3: return JOIN_DIST_PARTITIONED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<JQuickJoinDistributionProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      JQuickJoinDistributionProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<JQuickJoinDistributionProto>() {
          public JQuickJoinDistributionProto findValueByNumber(int number) {
            return JQuickJoinDistributionProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.getDescriptor().getEnumTypes().get(6);
  }

  private static final JQuickJoinDistributionProto[] VALUES = values();

  public static JQuickJoinDistributionProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private JQuickJoinDistributionProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.github.paohaijiao.proto.JQuickJoinDistributionProto)
}

