// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

public interface JQuickNestedLoopJoinNodeProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.paohaijiao.proto.JQuickNestedLoopJoinNodeProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.github.paohaijiao.proto.JQuickJoinTypeProto join_type = 1;</code>
   * @return The enum numeric value on the wire for joinType.
   */
  int getJoinTypeValue();
  /**
   * <code>.com.github.paohaijiao.proto.JQuickJoinTypeProto join_type = 1;</code>
   * @return The joinType.
   */
  com.github.paohaijiao.proto.JQuickJoinTypeProto getJoinType();

  /**
   * <code>.com.github.paohaijiao.proto.JQuickExpressionProto condition = 2;</code>
   * @return Whether the condition field is set.
   */
  boolean hasCondition();
  /**
   * <code>.com.github.paohaijiao.proto.JQuickExpressionProto condition = 2;</code>
   * @return The condition.
   */
  com.github.paohaijiao.proto.JQuickExpressionProto getCondition();
  /**
   * <code>.com.github.paohaijiao.proto.JQuickExpressionProto condition = 2;</code>
   */
  com.github.paohaijiao.proto.JQuickExpressionProtoOrBuilder getConditionOrBuilder();
}
