// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

public interface JQuickUpdateWorkerEndpointsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.paohaijiao.proto.JQuickUpdateWorkerEndpointsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 endpoint_count = 3;</code>
   * @return The endpointCount.
   */
  int getEndpointCount();
}
