// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

/**
 * <pre>
 * 注册 Worker 响应
 * </pre>
 *
 * Protobuf type {@code com.github.paohaijiao.proto.JQuickRegisterWorkerResponse}
 */
public final class JQuickRegisterWorkerResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.paohaijiao.proto.JQuickRegisterWorkerResponse)
    JQuickRegisterWorkerResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JQuickRegisterWorkerResponse.newBuilder() to construct.
  private JQuickRegisterWorkerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JQuickRegisterWorkerResponse() {
    message_ = "";
    coordinatorId_ = "";
    allWorkers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JQuickRegisterWorkerResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickRegisterWorkerResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickRegisterWorkerResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.paohaijiao.proto.JQuickRegisterWorkerResponse.class, com.github.paohaijiao.proto.JQuickRegisterWorkerResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COORDINATOR_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object coordinatorId_ = "";
  /**
   * <code>string coordinator_id = 3;</code>
   * @return The coordinatorId.
   */
  @java.lang.Override
  public java.lang.String getCoordinatorId() {
    java.lang.Object ref = coordinatorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      coordinatorId_ = s;
      return s;
    }
  }
  /**
   * <code>string coordinator_id = 3;</code>
   * @return The bytes for coordinatorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCoordinatorIdBytes() {
    java.lang.Object ref = coordinatorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      coordinatorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALL_WORKERS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.github.paohaijiao.proto.JQuickWorkerEndpointProto> allWorkers_;
  /**
   * <pre>
   * 所有已注册的 Worker
   * </pre>
   *
   * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.paohaijiao.proto.JQuickWorkerEndpointProto> getAllWorkersList() {
    return allWorkers_;
  }
  /**
   * <pre>
   * 所有已注册的 Worker
   * </pre>
   *
   * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder> 
      getAllWorkersOrBuilderList() {
    return allWorkers_;
  }
  /**
   * <pre>
   * 所有已注册的 Worker
   * </pre>
   *
   * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
   */
  @java.lang.Override
  public int getAllWorkersCount() {
    return allWorkers_.size();
  }
  /**
   * <pre>
   * 所有已注册的 Worker
   * </pre>
   *
   * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
   */
  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickWorkerEndpointProto getAllWorkers(int index) {
    return allWorkers_.get(index);
  }
  /**
   * <pre>
   * 所有已注册的 Worker
   * </pre>
   *
   * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
   */
  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder getAllWorkersOrBuilder(
      int index) {
    return allWorkers_.get(index);
  }

  public static final int ASSIGNED_ENDPOINT_FIELD_NUMBER = 5;
  private com.github.paohaijiao.proto.JQuickWorkerEndpointProto assignedEndpoint_;
  /**
   * <pre>
   * 当前 Worker 的端点信息
   * </pre>
   *
   * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
   * @return Whether the assignedEndpoint field is set.
   */
  @java.lang.Override
  public boolean hasAssignedEndpoint() {
    return assignedEndpoint_ != null;
  }
  /**
   * <pre>
   * 当前 Worker 的端点信息
   * </pre>
   *
   * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
   * @return The assignedEndpoint.
   */
  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickWorkerEndpointProto getAssignedEndpoint() {
    return assignedEndpoint_ == null ? com.github.paohaijiao.proto.JQuickWorkerEndpointProto.getDefaultInstance() : assignedEndpoint_;
  }
  /**
   * <pre>
   * 当前 Worker 的端点信息
   * </pre>
   *
   * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
   */
  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder getAssignedEndpointOrBuilder() {
    return assignedEndpoint_ == null ? com.github.paohaijiao.proto.JQuickWorkerEndpointProto.getDefaultInstance() : assignedEndpoint_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(coordinatorId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, coordinatorId_);
    }
    for (int i = 0; i < allWorkers_.size(); i++) {
      output.writeMessage(4, allWorkers_.get(i));
    }
    if (assignedEndpoint_ != null) {
      output.writeMessage(5, getAssignedEndpoint());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(coordinatorId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, coordinatorId_);
    }
    for (int i = 0; i < allWorkers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, allWorkers_.get(i));
    }
    if (assignedEndpoint_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAssignedEndpoint());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.paohaijiao.proto.JQuickRegisterWorkerResponse)) {
      return super.equals(obj);
    }
    com.github.paohaijiao.proto.JQuickRegisterWorkerResponse other = (com.github.paohaijiao.proto.JQuickRegisterWorkerResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getCoordinatorId()
        .equals(other.getCoordinatorId())) return false;
    if (!getAllWorkersList()
        .equals(other.getAllWorkersList())) return false;
    if (hasAssignedEndpoint() != other.hasAssignedEndpoint()) return false;
    if (hasAssignedEndpoint()) {
      if (!getAssignedEndpoint()
          .equals(other.getAssignedEndpoint())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + COORDINATOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCoordinatorId().hashCode();
    if (getAllWorkersCount() > 0) {
      hash = (37 * hash) + ALL_WORKERS_FIELD_NUMBER;
      hash = (53 * hash) + getAllWorkersList().hashCode();
    }
    if (hasAssignedEndpoint()) {
      hash = (37 * hash) + ASSIGNED_ENDPOINT_FIELD_NUMBER;
      hash = (53 * hash) + getAssignedEndpoint().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.paohaijiao.proto.JQuickRegisterWorkerResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 注册 Worker 响应
   * </pre>
   *
   * Protobuf type {@code com.github.paohaijiao.proto.JQuickRegisterWorkerResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.paohaijiao.proto.JQuickRegisterWorkerResponse)
      com.github.paohaijiao.proto.JQuickRegisterWorkerResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickRegisterWorkerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickRegisterWorkerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.paohaijiao.proto.JQuickRegisterWorkerResponse.class, com.github.paohaijiao.proto.JQuickRegisterWorkerResponse.Builder.class);
    }

    // Construct using com.github.paohaijiao.proto.JQuickRegisterWorkerResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      message_ = "";
      coordinatorId_ = "";
      if (allWorkersBuilder_ == null) {
        allWorkers_ = java.util.Collections.emptyList();
      } else {
        allWorkers_ = null;
        allWorkersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      assignedEndpoint_ = null;
      if (assignedEndpointBuilder_ != null) {
        assignedEndpointBuilder_.dispose();
        assignedEndpointBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.paohaijiao.proto.JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickRegisterWorkerResponse_descriptor;
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickRegisterWorkerResponse getDefaultInstanceForType() {
      return com.github.paohaijiao.proto.JQuickRegisterWorkerResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickRegisterWorkerResponse build() {
      com.github.paohaijiao.proto.JQuickRegisterWorkerResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.paohaijiao.proto.JQuickRegisterWorkerResponse buildPartial() {
      com.github.paohaijiao.proto.JQuickRegisterWorkerResponse result = new com.github.paohaijiao.proto.JQuickRegisterWorkerResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.github.paohaijiao.proto.JQuickRegisterWorkerResponse result) {
      if (allWorkersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          allWorkers_ = java.util.Collections.unmodifiableList(allWorkers_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.allWorkers_ = allWorkers_;
      } else {
        result.allWorkers_ = allWorkersBuilder_.build();
      }
    }

    private void buildPartial0(com.github.paohaijiao.proto.JQuickRegisterWorkerResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.coordinatorId_ = coordinatorId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.assignedEndpoint_ = assignedEndpointBuilder_ == null
            ? assignedEndpoint_
            : assignedEndpointBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.paohaijiao.proto.JQuickRegisterWorkerResponse) {
        return mergeFrom((com.github.paohaijiao.proto.JQuickRegisterWorkerResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.paohaijiao.proto.JQuickRegisterWorkerResponse other) {
      if (other == com.github.paohaijiao.proto.JQuickRegisterWorkerResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getCoordinatorId().isEmpty()) {
        coordinatorId_ = other.coordinatorId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (allWorkersBuilder_ == null) {
        if (!other.allWorkers_.isEmpty()) {
          if (allWorkers_.isEmpty()) {
            allWorkers_ = other.allWorkers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAllWorkersIsMutable();
            allWorkers_.addAll(other.allWorkers_);
          }
          onChanged();
        }
      } else {
        if (!other.allWorkers_.isEmpty()) {
          if (allWorkersBuilder_.isEmpty()) {
            allWorkersBuilder_.dispose();
            allWorkersBuilder_ = null;
            allWorkers_ = other.allWorkers_;
            bitField0_ = (bitField0_ & ~0x00000008);
            allWorkersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAllWorkersFieldBuilder() : null;
          } else {
            allWorkersBuilder_.addAllMessages(other.allWorkers_);
          }
        }
      }
      if (other.hasAssignedEndpoint()) {
        mergeAssignedEndpoint(other.getAssignedEndpoint());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              coordinatorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.github.paohaijiao.proto.JQuickWorkerEndpointProto m =
                  input.readMessage(
                      com.github.paohaijiao.proto.JQuickWorkerEndpointProto.parser(),
                      extensionRegistry);
              if (allWorkersBuilder_ == null) {
                ensureAllWorkersIsMutable();
                allWorkers_.add(m);
              } else {
                allWorkersBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getAssignedEndpointFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object coordinatorId_ = "";
    /**
     * <code>string coordinator_id = 3;</code>
     * @return The coordinatorId.
     */
    public java.lang.String getCoordinatorId() {
      java.lang.Object ref = coordinatorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        coordinatorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string coordinator_id = 3;</code>
     * @return The bytes for coordinatorId.
     */
    public com.google.protobuf.ByteString
        getCoordinatorIdBytes() {
      java.lang.Object ref = coordinatorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coordinatorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string coordinator_id = 3;</code>
     * @param value The coordinatorId to set.
     * @return This builder for chaining.
     */
    public Builder setCoordinatorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      coordinatorId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string coordinator_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoordinatorId() {
      coordinatorId_ = getDefaultInstance().getCoordinatorId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string coordinator_id = 3;</code>
     * @param value The bytes for coordinatorId to set.
     * @return This builder for chaining.
     */
    public Builder setCoordinatorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      coordinatorId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<com.github.paohaijiao.proto.JQuickWorkerEndpointProto> allWorkers_ =
      java.util.Collections.emptyList();
    private void ensureAllWorkersIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        allWorkers_ = new java.util.ArrayList<com.github.paohaijiao.proto.JQuickWorkerEndpointProto>(allWorkers_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.paohaijiao.proto.JQuickWorkerEndpointProto, com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder, com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder> allWorkersBuilder_;

    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public java.util.List<com.github.paohaijiao.proto.JQuickWorkerEndpointProto> getAllWorkersList() {
      if (allWorkersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(allWorkers_);
      } else {
        return allWorkersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public int getAllWorkersCount() {
      if (allWorkersBuilder_ == null) {
        return allWorkers_.size();
      } else {
        return allWorkersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public com.github.paohaijiao.proto.JQuickWorkerEndpointProto getAllWorkers(int index) {
      if (allWorkersBuilder_ == null) {
        return allWorkers_.get(index);
      } else {
        return allWorkersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public Builder setAllWorkers(
        int index, com.github.paohaijiao.proto.JQuickWorkerEndpointProto value) {
      if (allWorkersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllWorkersIsMutable();
        allWorkers_.set(index, value);
        onChanged();
      } else {
        allWorkersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public Builder setAllWorkers(
        int index, com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder builderForValue) {
      if (allWorkersBuilder_ == null) {
        ensureAllWorkersIsMutable();
        allWorkers_.set(index, builderForValue.build());
        onChanged();
      } else {
        allWorkersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public Builder addAllWorkers(com.github.paohaijiao.proto.JQuickWorkerEndpointProto value) {
      if (allWorkersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllWorkersIsMutable();
        allWorkers_.add(value);
        onChanged();
      } else {
        allWorkersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public Builder addAllWorkers(
        int index, com.github.paohaijiao.proto.JQuickWorkerEndpointProto value) {
      if (allWorkersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllWorkersIsMutable();
        allWorkers_.add(index, value);
        onChanged();
      } else {
        allWorkersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public Builder addAllWorkers(
        com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder builderForValue) {
      if (allWorkersBuilder_ == null) {
        ensureAllWorkersIsMutable();
        allWorkers_.add(builderForValue.build());
        onChanged();
      } else {
        allWorkersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public Builder addAllWorkers(
        int index, com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder builderForValue) {
      if (allWorkersBuilder_ == null) {
        ensureAllWorkersIsMutable();
        allWorkers_.add(index, builderForValue.build());
        onChanged();
      } else {
        allWorkersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public Builder addAllAllWorkers(
        java.lang.Iterable<? extends com.github.paohaijiao.proto.JQuickWorkerEndpointProto> values) {
      if (allWorkersBuilder_ == null) {
        ensureAllWorkersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, allWorkers_);
        onChanged();
      } else {
        allWorkersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public Builder clearAllWorkers() {
      if (allWorkersBuilder_ == null) {
        allWorkers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        allWorkersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public Builder removeAllWorkers(int index) {
      if (allWorkersBuilder_ == null) {
        ensureAllWorkersIsMutable();
        allWorkers_.remove(index);
        onChanged();
      } else {
        allWorkersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder getAllWorkersBuilder(
        int index) {
      return getAllWorkersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder getAllWorkersOrBuilder(
        int index) {
      if (allWorkersBuilder_ == null) {
        return allWorkers_.get(index);  } else {
        return allWorkersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public java.util.List<? extends com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder> 
         getAllWorkersOrBuilderList() {
      if (allWorkersBuilder_ != null) {
        return allWorkersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(allWorkers_);
      }
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder addAllWorkersBuilder() {
      return getAllWorkersFieldBuilder().addBuilder(
          com.github.paohaijiao.proto.JQuickWorkerEndpointProto.getDefaultInstance());
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder addAllWorkersBuilder(
        int index) {
      return getAllWorkersFieldBuilder().addBuilder(
          index, com.github.paohaijiao.proto.JQuickWorkerEndpointProto.getDefaultInstance());
    }
    /**
     * <pre>
     * 所有已注册的 Worker
     * </pre>
     *
     * <code>repeated .com.github.paohaijiao.proto.JQuickWorkerEndpointProto all_workers = 4;</code>
     */
    public java.util.List<com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder> 
         getAllWorkersBuilderList() {
      return getAllWorkersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.paohaijiao.proto.JQuickWorkerEndpointProto, com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder, com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder> 
        getAllWorkersFieldBuilder() {
      if (allWorkersBuilder_ == null) {
        allWorkersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.paohaijiao.proto.JQuickWorkerEndpointProto, com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder, com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder>(
                allWorkers_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        allWorkers_ = null;
      }
      return allWorkersBuilder_;
    }

    private com.github.paohaijiao.proto.JQuickWorkerEndpointProto assignedEndpoint_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.paohaijiao.proto.JQuickWorkerEndpointProto, com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder, com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder> assignedEndpointBuilder_;
    /**
     * <pre>
     * 当前 Worker 的端点信息
     * </pre>
     *
     * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
     * @return Whether the assignedEndpoint field is set.
     */
    public boolean hasAssignedEndpoint() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 当前 Worker 的端点信息
     * </pre>
     *
     * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
     * @return The assignedEndpoint.
     */
    public com.github.paohaijiao.proto.JQuickWorkerEndpointProto getAssignedEndpoint() {
      if (assignedEndpointBuilder_ == null) {
        return assignedEndpoint_ == null ? com.github.paohaijiao.proto.JQuickWorkerEndpointProto.getDefaultInstance() : assignedEndpoint_;
      } else {
        return assignedEndpointBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 当前 Worker 的端点信息
     * </pre>
     *
     * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
     */
    public Builder setAssignedEndpoint(com.github.paohaijiao.proto.JQuickWorkerEndpointProto value) {
      if (assignedEndpointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        assignedEndpoint_ = value;
      } else {
        assignedEndpointBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前 Worker 的端点信息
     * </pre>
     *
     * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
     */
    public Builder setAssignedEndpoint(
        com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder builderForValue) {
      if (assignedEndpointBuilder_ == null) {
        assignedEndpoint_ = builderForValue.build();
      } else {
        assignedEndpointBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前 Worker 的端点信息
     * </pre>
     *
     * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
     */
    public Builder mergeAssignedEndpoint(com.github.paohaijiao.proto.JQuickWorkerEndpointProto value) {
      if (assignedEndpointBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          assignedEndpoint_ != null &&
          assignedEndpoint_ != com.github.paohaijiao.proto.JQuickWorkerEndpointProto.getDefaultInstance()) {
          getAssignedEndpointBuilder().mergeFrom(value);
        } else {
          assignedEndpoint_ = value;
        }
      } else {
        assignedEndpointBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前 Worker 的端点信息
     * </pre>
     *
     * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
     */
    public Builder clearAssignedEndpoint() {
      bitField0_ = (bitField0_ & ~0x00000010);
      assignedEndpoint_ = null;
      if (assignedEndpointBuilder_ != null) {
        assignedEndpointBuilder_.dispose();
        assignedEndpointBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前 Worker 的端点信息
     * </pre>
     *
     * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
     */
    public com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder getAssignedEndpointBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getAssignedEndpointFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 当前 Worker 的端点信息
     * </pre>
     *
     * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
     */
    public com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder getAssignedEndpointOrBuilder() {
      if (assignedEndpointBuilder_ != null) {
        return assignedEndpointBuilder_.getMessageOrBuilder();
      } else {
        return assignedEndpoint_ == null ?
            com.github.paohaijiao.proto.JQuickWorkerEndpointProto.getDefaultInstance() : assignedEndpoint_;
      }
    }
    /**
     * <pre>
     * 当前 Worker 的端点信息
     * </pre>
     *
     * <code>.com.github.paohaijiao.proto.JQuickWorkerEndpointProto assigned_endpoint = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.paohaijiao.proto.JQuickWorkerEndpointProto, com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder, com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder> 
        getAssignedEndpointFieldBuilder() {
      if (assignedEndpointBuilder_ == null) {
        assignedEndpointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.paohaijiao.proto.JQuickWorkerEndpointProto, com.github.paohaijiao.proto.JQuickWorkerEndpointProto.Builder, com.github.paohaijiao.proto.JQuickWorkerEndpointProtoOrBuilder>(
                getAssignedEndpoint(),
                getParentForChildren(),
                isClean());
        assignedEndpoint_ = null;
      }
      return assignedEndpointBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.paohaijiao.proto.JQuickRegisterWorkerResponse)
  }

  // @@protoc_insertion_point(class_scope:com.github.paohaijiao.proto.JQuickRegisterWorkerResponse)
  private static final com.github.paohaijiao.proto.JQuickRegisterWorkerResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.paohaijiao.proto.JQuickRegisterWorkerResponse();
  }

  public static com.github.paohaijiao.proto.JQuickRegisterWorkerResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JQuickRegisterWorkerResponse>
      PARSER = new com.google.protobuf.AbstractParser<JQuickRegisterWorkerResponse>() {
    @java.lang.Override
    public JQuickRegisterWorkerResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JQuickRegisterWorkerResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JQuickRegisterWorkerResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.paohaijiao.proto.JQuickRegisterWorkerResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

