// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

public interface JQuickHeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.paohaijiao.proto.JQuickHeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string worker_id = 1;</code>
   * @return The workerId.
   */
  java.lang.String getWorkerId();
  /**
   * <code>string worker_id = 1;</code>
   * @return The bytes for workerId.
   */
  com.google.protobuf.ByteString
      getWorkerIdBytes();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>int32 current_tasks = 3;</code>
   * @return The currentTasks.
   */
  int getCurrentTasks();

  /**
   * <code>double cpu_usage = 4;</code>
   * @return The cpuUsage.
   */
  double getCpuUsage();

  /**
   * <code>double memory_usage = 5;</code>
   * @return The memoryUsage.
   */
  double getMemoryUsage();

  /**
   * <code>int64 memory_available = 6;</code>
   * @return The memoryAvailable.
   */
  long getMemoryAvailable();

  /**
   * <code>repeated string completed_task_ids = 7;</code>
   * @return A list containing the completedTaskIds.
   */
  java.util.List<java.lang.String>
      getCompletedTaskIdsList();
  /**
   * <code>repeated string completed_task_ids = 7;</code>
   * @return The count of completedTaskIds.
   */
  int getCompletedTaskIdsCount();
  /**
   * <code>repeated string completed_task_ids = 7;</code>
   * @param index The index of the element to return.
   * @return The completedTaskIds at the given index.
   */
  java.lang.String getCompletedTaskIds(int index);
  /**
   * <code>repeated string completed_task_ids = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the completedTaskIds at the given index.
   */
  com.google.protobuf.ByteString
      getCompletedTaskIdsBytes(int index);

  /**
   * <pre>
   * 分区内存使用情况
   * </pre>
   *
   * <code>map&lt;string, int64&gt; partition_memory_usage = 8;</code>
   */
  int getPartitionMemoryUsageCount();
  /**
   * <pre>
   * 分区内存使用情况
   * </pre>
   *
   * <code>map&lt;string, int64&gt; partition_memory_usage = 8;</code>
   */
  boolean containsPartitionMemoryUsage(
      java.lang.String key);
  /**
   * Use {@link #getPartitionMemoryUsageMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getPartitionMemoryUsage();
  /**
   * <pre>
   * 分区内存使用情况
   * </pre>
   *
   * <code>map&lt;string, int64&gt; partition_memory_usage = 8;</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getPartitionMemoryUsageMap();
  /**
   * <pre>
   * 分区内存使用情况
   * </pre>
   *
   * <code>map&lt;string, int64&gt; partition_memory_usage = 8;</code>
   */
  long getPartitionMemoryUsageOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <pre>
   * 分区内存使用情况
   * </pre>
   *
   * <code>map&lt;string, int64&gt; partition_memory_usage = 8;</code>
   */
  long getPartitionMemoryUsageOrThrow(
      java.lang.String key);
}
