// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

/**
 * Protobuf type {@code com.github.paohaijiao.proto.JQuickWorkerInfoProto}
 */
public final class JQuickWorkerInfoProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.paohaijiao.proto.JQuickWorkerInfoProto)
    JQuickWorkerInfoProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JQuickWorkerInfoProto.newBuilder() to construct.
  private JQuickWorkerInfoProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JQuickWorkerInfoProto() {
    workerId_ = "";
    host_ = "";
    localPartitionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new JQuickWorkerInfoProto();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickWorkerInfoProto_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickWorkerInfoProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            JQuickWorkerInfoProto.class, Builder.class);
  }

  public static final int WORKER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object workerId_ = "";
  /**
   * <code>string worker_id = 1;</code>
   * @return The workerId.
   */
  @Override
  public String getWorkerId() {
    Object ref = workerId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      workerId_ = s;
      return s;
    }
  }
  /**
   * <code>string worker_id = 1;</code>
   * @return The bytes for workerId.
   */
  @Override
  public com.google.protobuf.ByteString
      getWorkerIdBytes() {
    Object ref = workerId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      workerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOST_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object host_ = "";
  /**
   * <code>string host = 2;</code>
   * @return The host.
   */
  @Override
  public String getHost() {
    Object ref = host_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      host_ = s;
      return s;
    }
  }
  /**
   * <code>string host = 2;</code>
   * @return The bytes for host.
   */
  @Override
  public com.google.protobuf.ByteString
      getHostBytes() {
    Object ref = host_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      host_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 3;
  private int port_ = 0;
  /**
   * <code>int32 port = 3;</code>
   * @return The port.
   */
  @Override
  public int getPort() {
    return port_;
  }

  public static final int MAX_PARALLELISM_FIELD_NUMBER = 4;
  private int maxParallelism_ = 0;
  /**
   * <code>int32 max_parallelism = 4;</code>
   * @return The maxParallelism.
   */
  @Override
  public int getMaxParallelism() {
    return maxParallelism_;
  }

  public static final int CURRENT_TASKS_FIELD_NUMBER = 5;
  private int currentTasks_ = 0;
  /**
   * <code>int32 current_tasks = 5;</code>
   * @return The currentTasks.
   */
  @Override
  public int getCurrentTasks() {
    return currentTasks_;
  }

  public static final int CPU_USAGE_FIELD_NUMBER = 6;
  private double cpuUsage_ = 0D;
  /**
   * <code>double cpu_usage = 6;</code>
   * @return The cpuUsage.
   */
  @Override
  public double getCpuUsage() {
    return cpuUsage_;
  }

  public static final int MEMORY_USAGE_FIELD_NUMBER = 7;
  private double memoryUsage_ = 0D;
  /**
   * <code>double memory_usage = 7;</code>
   * @return The memoryUsage.
   */
  @Override
  public double getMemoryUsage() {
    return memoryUsage_;
  }

  public static final int AVAILABLE_MEMORY_BYTES_FIELD_NUMBER = 8;
  private long availableMemoryBytes_ = 0L;
  /**
   * <pre>
   * 可用内存（字节）
   * </pre>
   *
   * <code>int64 available_memory_bytes = 8;</code>
   * @return The availableMemoryBytes.
   */
  @Override
  public long getAvailableMemoryBytes() {
    return availableMemoryBytes_;
  }

  public static final int USED_MEMORY_BYTES_FIELD_NUMBER = 9;
  private long usedMemoryBytes_ = 0L;
  /**
   * <pre>
   * 已用内存
   * </pre>
   *
   * <code>int64 used_memory_bytes = 9;</code>
   * @return The usedMemoryBytes.
   */
  @Override
  public long getUsedMemoryBytes() {
    return usedMemoryBytes_;
  }

  public static final int HEALTHY_FIELD_NUMBER = 10;
  private boolean healthy_ = false;
  /**
   * <code>bool healthy = 10;</code>
   * @return The healthy.
   */
  @Override
  public boolean getHealthy() {
    return healthy_;
  }

  public static final int LAST_HEARTBEAT_FIELD_NUMBER = 11;
  private long lastHeartbeat_ = 0L;
  /**
   * <code>int64 last_heartbeat = 11;</code>
   * @return The lastHeartbeat.
   */
  @Override
  public long getLastHeartbeat() {
    return lastHeartbeat_;
  }

  public static final int LOCAL_PARTITION_IDS_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList localPartitionIds_;
  /**
   * <pre>
   * 本地内存中的分区ID
   * </pre>
   *
   * <code>repeated string local_partition_ids = 12;</code>
   * @return A list containing the localPartitionIds.
   */
  public com.google.protobuf.ProtocolStringList
      getLocalPartitionIdsList() {
    return localPartitionIds_;
  }
  /**
   * <pre>
   * 本地内存中的分区ID
   * </pre>
   *
   * <code>repeated string local_partition_ids = 12;</code>
   * @return The count of localPartitionIds.
   */
  public int getLocalPartitionIdsCount() {
    return localPartitionIds_.size();
  }
  /**
   * <pre>
   * 本地内存中的分区ID
   * </pre>
   *
   * <code>repeated string local_partition_ids = 12;</code>
   * @param index The index of the element to return.
   * @return The localPartitionIds at the given index.
   */
  public String getLocalPartitionIds(int index) {
    return localPartitionIds_.get(index);
  }
  /**
   * <pre>
   * 本地内存中的分区ID
   * </pre>
   *
   * <code>repeated string local_partition_ids = 12;</code>
   * @param index The index of the value to return.
   * @return The bytes of the localPartitionIds at the given index.
   */
  public com.google.protobuf.ByteString
      getLocalPartitionIdsBytes(int index) {
    return localPartitionIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workerId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, host_);
    }
    if (port_ != 0) {
      output.writeInt32(3, port_);
    }
    if (maxParallelism_ != 0) {
      output.writeInt32(4, maxParallelism_);
    }
    if (currentTasks_ != 0) {
      output.writeInt32(5, currentTasks_);
    }
    if (Double.doubleToRawLongBits(cpuUsage_) != 0) {
      output.writeDouble(6, cpuUsage_);
    }
    if (Double.doubleToRawLongBits(memoryUsage_) != 0) {
      output.writeDouble(7, memoryUsage_);
    }
    if (availableMemoryBytes_ != 0L) {
      output.writeInt64(8, availableMemoryBytes_);
    }
    if (usedMemoryBytes_ != 0L) {
      output.writeInt64(9, usedMemoryBytes_);
    }
    if (healthy_ != false) {
      output.writeBool(10, healthy_);
    }
    if (lastHeartbeat_ != 0L) {
      output.writeInt64(11, lastHeartbeat_);
    }
    for (int i = 0; i < localPartitionIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, localPartitionIds_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workerId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, host_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, port_);
    }
    if (maxParallelism_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, maxParallelism_);
    }
    if (currentTasks_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, currentTasks_);
    }
    if (Double.doubleToRawLongBits(cpuUsage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, cpuUsage_);
    }
    if (Double.doubleToRawLongBits(memoryUsage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, memoryUsage_);
    }
    if (availableMemoryBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, availableMemoryBytes_);
    }
    if (usedMemoryBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, usedMemoryBytes_);
    }
    if (healthy_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, healthy_);
    }
    if (lastHeartbeat_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, lastHeartbeat_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < localPartitionIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(localPartitionIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLocalPartitionIdsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof JQuickWorkerInfoProto)) {
      return super.equals(obj);
    }
    JQuickWorkerInfoProto other = (JQuickWorkerInfoProto) obj;

    if (!getWorkerId()
        .equals(other.getWorkerId())) return false;
    if (!getHost()
        .equals(other.getHost())) return false;
    if (getPort()
        != other.getPort()) return false;
    if (getMaxParallelism()
        != other.getMaxParallelism()) return false;
    if (getCurrentTasks()
        != other.getCurrentTasks()) return false;
    if (Double.doubleToLongBits(getCpuUsage())
        != Double.doubleToLongBits(
            other.getCpuUsage())) return false;
    if (Double.doubleToLongBits(getMemoryUsage())
        != Double.doubleToLongBits(
            other.getMemoryUsage())) return false;
    if (getAvailableMemoryBytes()
        != other.getAvailableMemoryBytes()) return false;
    if (getUsedMemoryBytes()
        != other.getUsedMemoryBytes()) return false;
    if (getHealthy()
        != other.getHealthy()) return false;
    if (getLastHeartbeat()
        != other.getLastHeartbeat()) return false;
    if (!getLocalPartitionIdsList()
        .equals(other.getLocalPartitionIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WORKER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerId().hashCode();
    hash = (37 * hash) + HOST_FIELD_NUMBER;
    hash = (53 * hash) + getHost().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (37 * hash) + MAX_PARALLELISM_FIELD_NUMBER;
    hash = (53 * hash) + getMaxParallelism();
    hash = (37 * hash) + CURRENT_TASKS_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentTasks();
    hash = (37 * hash) + CPU_USAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getCpuUsage()));
    hash = (37 * hash) + MEMORY_USAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getMemoryUsage()));
    hash = (37 * hash) + AVAILABLE_MEMORY_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAvailableMemoryBytes());
    hash = (37 * hash) + USED_MEMORY_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUsedMemoryBytes());
    hash = (37 * hash) + HEALTHY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHealthy());
    hash = (37 * hash) + LAST_HEARTBEAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastHeartbeat());
    if (getLocalPartitionIdsCount() > 0) {
      hash = (37 * hash) + LOCAL_PARTITION_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getLocalPartitionIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static JQuickWorkerInfoProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JQuickWorkerInfoProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JQuickWorkerInfoProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JQuickWorkerInfoProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JQuickWorkerInfoProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JQuickWorkerInfoProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JQuickWorkerInfoProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JQuickWorkerInfoProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static JQuickWorkerInfoProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static JQuickWorkerInfoProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static JQuickWorkerInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JQuickWorkerInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(JQuickWorkerInfoProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.paohaijiao.proto.JQuickWorkerInfoProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.paohaijiao.proto.JQuickWorkerInfoProto)
      JQuickWorkerInfoProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickWorkerInfoProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickWorkerInfoProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JQuickWorkerInfoProto.class, Builder.class);
    }

    // Construct using com.github.paohaijiao.proto.JQuickWorkerInfoProto.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      workerId_ = "";
      host_ = "";
      port_ = 0;
      maxParallelism_ = 0;
      currentTasks_ = 0;
      cpuUsage_ = 0D;
      memoryUsage_ = 0D;
      availableMemoryBytes_ = 0L;
      usedMemoryBytes_ = 0L;
      healthy_ = false;
      lastHeartbeat_ = 0L;
      localPartitionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000800);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickWorkerInfoProto_descriptor;
    }

    @Override
    public JQuickWorkerInfoProto getDefaultInstanceForType() {
      return JQuickWorkerInfoProto.getDefaultInstance();
    }

    @Override
    public JQuickWorkerInfoProto build() {
      JQuickWorkerInfoProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public JQuickWorkerInfoProto buildPartial() {
      JQuickWorkerInfoProto result = new JQuickWorkerInfoProto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(JQuickWorkerInfoProto result) {
      if (((bitField0_ & 0x00000800) != 0)) {
        localPartitionIds_ = localPartitionIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000800);
      }
      result.localPartitionIds_ = localPartitionIds_;
    }

    private void buildPartial0(JQuickWorkerInfoProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.workerId_ = workerId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.host_ = host_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.port_ = port_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.maxParallelism_ = maxParallelism_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.currentTasks_ = currentTasks_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.cpuUsage_ = cpuUsage_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.memoryUsage_ = memoryUsage_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.availableMemoryBytes_ = availableMemoryBytes_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.usedMemoryBytes_ = usedMemoryBytes_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.healthy_ = healthy_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.lastHeartbeat_ = lastHeartbeat_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof JQuickWorkerInfoProto) {
        return mergeFrom((JQuickWorkerInfoProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(JQuickWorkerInfoProto other) {
      if (other == JQuickWorkerInfoProto.getDefaultInstance()) return this;
      if (!other.getWorkerId().isEmpty()) {
        workerId_ = other.workerId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getHost().isEmpty()) {
        host_ = other.host_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      if (other.getMaxParallelism() != 0) {
        setMaxParallelism(other.getMaxParallelism());
      }
      if (other.getCurrentTasks() != 0) {
        setCurrentTasks(other.getCurrentTasks());
      }
      if (other.getCpuUsage() != 0D) {
        setCpuUsage(other.getCpuUsage());
      }
      if (other.getMemoryUsage() != 0D) {
        setMemoryUsage(other.getMemoryUsage());
      }
      if (other.getAvailableMemoryBytes() != 0L) {
        setAvailableMemoryBytes(other.getAvailableMemoryBytes());
      }
      if (other.getUsedMemoryBytes() != 0L) {
        setUsedMemoryBytes(other.getUsedMemoryBytes());
      }
      if (other.getHealthy() != false) {
        setHealthy(other.getHealthy());
      }
      if (other.getLastHeartbeat() != 0L) {
        setLastHeartbeat(other.getLastHeartbeat());
      }
      if (!other.localPartitionIds_.isEmpty()) {
        if (localPartitionIds_.isEmpty()) {
          localPartitionIds_ = other.localPartitionIds_;
          bitField0_ = (bitField0_ & ~0x00000800);
        } else {
          ensureLocalPartitionIdsIsMutable();
          localPartitionIds_.addAll(other.localPartitionIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              workerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              host_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              port_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              maxParallelism_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              currentTasks_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 49: {
              cpuUsage_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 57: {
              memoryUsage_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 64: {
              availableMemoryBytes_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              usedMemoryBytes_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              healthy_ = input.readBool();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              lastHeartbeat_ = input.readInt64();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 98: {
              String s = input.readStringRequireUtf8();
              ensureLocalPartitionIdsIsMutable();
              localPartitionIds_.add(s);
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object workerId_ = "";
    /**
     * <code>string worker_id = 1;</code>
     * @return The workerId.
     */
    public String getWorkerId() {
      Object ref = workerId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        workerId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string worker_id = 1;</code>
     * @return The bytes for workerId.
     */
    public com.google.protobuf.ByteString
        getWorkerIdBytes() {
      Object ref = workerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        workerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string worker_id = 1;</code>
     * @param value The workerId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      workerId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string worker_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkerId() {
      workerId_ = getDefaultInstance().getWorkerId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string worker_id = 1;</code>
     * @param value The bytes for workerId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      workerId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object host_ = "";
    /**
     * <code>string host = 2;</code>
     * @return The host.
     */
    public String getHost() {
      Object ref = host_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        host_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string host = 2;</code>
     * @return The bytes for host.
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string host = 2;</code>
     * @param value The host to set.
     * @return This builder for chaining.
     */
    public Builder setHost(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      host_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string host = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHost() {
      host_ = getDefaultInstance().getHost();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string host = 2;</code>
     * @param value The bytes for host to set.
     * @return This builder for chaining.
     */
    public Builder setHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      host_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <code>int32 port = 3;</code>
     * @return The port.
     */
    @Override
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 3;</code>
     * @param value The port to set.
     * @return This builder for chaining.
     */
    public Builder setPort(int value) {
      
      port_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 port = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPort() {
      bitField0_ = (bitField0_ & ~0x00000004);
      port_ = 0;
      onChanged();
      return this;
    }

    private int maxParallelism_ ;
    /**
     * <code>int32 max_parallelism = 4;</code>
     * @return The maxParallelism.
     */
    @Override
    public int getMaxParallelism() {
      return maxParallelism_;
    }
    /**
     * <code>int32 max_parallelism = 4;</code>
     * @param value The maxParallelism to set.
     * @return This builder for chaining.
     */
    public Builder setMaxParallelism(int value) {
      
      maxParallelism_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_parallelism = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxParallelism() {
      bitField0_ = (bitField0_ & ~0x00000008);
      maxParallelism_ = 0;
      onChanged();
      return this;
    }

    private int currentTasks_ ;
    /**
     * <code>int32 current_tasks = 5;</code>
     * @return The currentTasks.
     */
    @Override
    public int getCurrentTasks() {
      return currentTasks_;
    }
    /**
     * <code>int32 current_tasks = 5;</code>
     * @param value The currentTasks to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentTasks(int value) {
      
      currentTasks_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 current_tasks = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentTasks() {
      bitField0_ = (bitField0_ & ~0x00000010);
      currentTasks_ = 0;
      onChanged();
      return this;
    }

    private double cpuUsage_ ;
    /**
     * <code>double cpu_usage = 6;</code>
     * @return The cpuUsage.
     */
    @Override
    public double getCpuUsage() {
      return cpuUsage_;
    }
    /**
     * <code>double cpu_usage = 6;</code>
     * @param value The cpuUsage to set.
     * @return This builder for chaining.
     */
    public Builder setCpuUsage(double value) {
      
      cpuUsage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double cpu_usage = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpuUsage() {
      bitField0_ = (bitField0_ & ~0x00000020);
      cpuUsage_ = 0D;
      onChanged();
      return this;
    }

    private double memoryUsage_ ;
    /**
     * <code>double memory_usage = 7;</code>
     * @return The memoryUsage.
     */
    @Override
    public double getMemoryUsage() {
      return memoryUsage_;
    }
    /**
     * <code>double memory_usage = 7;</code>
     * @param value The memoryUsage to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryUsage(double value) {
      
      memoryUsage_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double memory_usage = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryUsage() {
      bitField0_ = (bitField0_ & ~0x00000040);
      memoryUsage_ = 0D;
      onChanged();
      return this;
    }

    private long availableMemoryBytes_ ;
    /**
     * <pre>
     * 可用内存（字节）
     * </pre>
     *
     * <code>int64 available_memory_bytes = 8;</code>
     * @return The availableMemoryBytes.
     */
    @Override
    public long getAvailableMemoryBytes() {
      return availableMemoryBytes_;
    }
    /**
     * <pre>
     * 可用内存（字节）
     * </pre>
     *
     * <code>int64 available_memory_bytes = 8;</code>
     * @param value The availableMemoryBytes to set.
     * @return This builder for chaining.
     */
    public Builder setAvailableMemoryBytes(long value) {
      
      availableMemoryBytes_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 可用内存（字节）
     * </pre>
     *
     * <code>int64 available_memory_bytes = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailableMemoryBytes() {
      bitField0_ = (bitField0_ & ~0x00000080);
      availableMemoryBytes_ = 0L;
      onChanged();
      return this;
    }

    private long usedMemoryBytes_ ;
    /**
     * <pre>
     * 已用内存
     * </pre>
     *
     * <code>int64 used_memory_bytes = 9;</code>
     * @return The usedMemoryBytes.
     */
    @Override
    public long getUsedMemoryBytes() {
      return usedMemoryBytes_;
    }
    /**
     * <pre>
     * 已用内存
     * </pre>
     *
     * <code>int64 used_memory_bytes = 9;</code>
     * @param value The usedMemoryBytes to set.
     * @return This builder for chaining.
     */
    public Builder setUsedMemoryBytes(long value) {
      
      usedMemoryBytes_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 已用内存
     * </pre>
     *
     * <code>int64 used_memory_bytes = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsedMemoryBytes() {
      bitField0_ = (bitField0_ & ~0x00000100);
      usedMemoryBytes_ = 0L;
      onChanged();
      return this;
    }

    private boolean healthy_ ;
    /**
     * <code>bool healthy = 10;</code>
     * @return The healthy.
     */
    @Override
    public boolean getHealthy() {
      return healthy_;
    }
    /**
     * <code>bool healthy = 10;</code>
     * @param value The healthy to set.
     * @return This builder for chaining.
     */
    public Builder setHealthy(boolean value) {
      
      healthy_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>bool healthy = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearHealthy() {
      bitField0_ = (bitField0_ & ~0x00000200);
      healthy_ = false;
      onChanged();
      return this;
    }

    private long lastHeartbeat_ ;
    /**
     * <code>int64 last_heartbeat = 11;</code>
     * @return The lastHeartbeat.
     */
    @Override
    public long getLastHeartbeat() {
      return lastHeartbeat_;
    }
    /**
     * <code>int64 last_heartbeat = 11;</code>
     * @param value The lastHeartbeat to set.
     * @return This builder for chaining.
     */
    public Builder setLastHeartbeat(long value) {
      
      lastHeartbeat_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_heartbeat = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastHeartbeat() {
      bitField0_ = (bitField0_ & ~0x00000400);
      lastHeartbeat_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList localPartitionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureLocalPartitionIdsIsMutable() {
      if (!((bitField0_ & 0x00000800) != 0)) {
        localPartitionIds_ = new com.google.protobuf.LazyStringArrayList(localPartitionIds_);
        bitField0_ |= 0x00000800;
       }
    }
    /**
     * <pre>
     * 本地内存中的分区ID
     * </pre>
     *
     * <code>repeated string local_partition_ids = 12;</code>
     * @return A list containing the localPartitionIds.
     */
    public com.google.protobuf.ProtocolStringList
        getLocalPartitionIdsList() {
      return localPartitionIds_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 本地内存中的分区ID
     * </pre>
     *
     * <code>repeated string local_partition_ids = 12;</code>
     * @return The count of localPartitionIds.
     */
    public int getLocalPartitionIdsCount() {
      return localPartitionIds_.size();
    }
    /**
     * <pre>
     * 本地内存中的分区ID
     * </pre>
     *
     * <code>repeated string local_partition_ids = 12;</code>
     * @param index The index of the element to return.
     * @return The localPartitionIds at the given index.
     */
    public String getLocalPartitionIds(int index) {
      return localPartitionIds_.get(index);
    }
    /**
     * <pre>
     * 本地内存中的分区ID
     * </pre>
     *
     * <code>repeated string local_partition_ids = 12;</code>
     * @param index The index of the value to return.
     * @return The bytes of the localPartitionIds at the given index.
     */
    public com.google.protobuf.ByteString
        getLocalPartitionIdsBytes(int index) {
      return localPartitionIds_.getByteString(index);
    }
    /**
     * <pre>
     * 本地内存中的分区ID
     * </pre>
     *
     * <code>repeated string local_partition_ids = 12;</code>
     * @param index The index to set the value at.
     * @param value The localPartitionIds to set.
     * @return This builder for chaining.
     */
    public Builder setLocalPartitionIds(
        int index, String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLocalPartitionIdsIsMutable();
      localPartitionIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 本地内存中的分区ID
     * </pre>
     *
     * <code>repeated string local_partition_ids = 12;</code>
     * @param value The localPartitionIds to add.
     * @return This builder for chaining.
     */
    public Builder addLocalPartitionIds(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLocalPartitionIdsIsMutable();
      localPartitionIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 本地内存中的分区ID
     * </pre>
     *
     * <code>repeated string local_partition_ids = 12;</code>
     * @param values The localPartitionIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllLocalPartitionIds(
        Iterable<String> values) {
      ensureLocalPartitionIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, localPartitionIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 本地内存中的分区ID
     * </pre>
     *
     * <code>repeated string local_partition_ids = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalPartitionIds() {
      localPartitionIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 本地内存中的分区ID
     * </pre>
     *
     * <code>repeated string local_partition_ids = 12;</code>
     * @param value The bytes of the localPartitionIds to add.
     * @return This builder for chaining.
     */
    public Builder addLocalPartitionIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLocalPartitionIdsIsMutable();
      localPartitionIds_.add(value);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.paohaijiao.proto.JQuickWorkerInfoProto)
  }

  // @@protoc_insertion_point(class_scope:com.github.paohaijiao.proto.JQuickWorkerInfoProto)
  private static final JQuickWorkerInfoProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new JQuickWorkerInfoProto();
  }

  public static JQuickWorkerInfoProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JQuickWorkerInfoProto>
      PARSER = new com.google.protobuf.AbstractParser<JQuickWorkerInfoProto>() {
    @Override
    public JQuickWorkerInfoProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JQuickWorkerInfoProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<JQuickWorkerInfoProto> getParserForType() {
    return PARSER;
  }

  @Override
  public JQuickWorkerInfoProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

