// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

/**
 * <pre>
 * 任务分配
 * </pre>
 *
 * Protobuf type {@code com.github.paohaijiao.proto.JQuickTaskAssignmentProto}
 */
public final class JQuickTaskAssignmentProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.paohaijiao.proto.JQuickTaskAssignmentProto)
    JQuickTaskAssignmentProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JQuickTaskAssignmentProto.newBuilder() to construct.
  private JQuickTaskAssignmentProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JQuickTaskAssignmentProto() {
    taskId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new JQuickTaskAssignmentProto();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTaskAssignmentProto_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTaskAssignmentProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            JQuickTaskAssignmentProto.class, Builder.class);
  }

  public static final int TASK_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object taskId_ = "";
  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  @Override
  public String getTaskId() {
    Object ref = taskId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  @Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    Object ref = taskId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FRAGMENT_FIELD_NUMBER = 2;
  private JQuickFragmentProto fragment_;
  /**
   * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
   * @return Whether the fragment field is set.
   */
  @Override
  public boolean hasFragment() {
    return fragment_ != null;
  }
  /**
   * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
   * @return The fragment.
   */
  @Override
  public JQuickFragmentProto getFragment() {
    return fragment_ == null ? JQuickFragmentProto.getDefaultInstance() : fragment_;
  }
  /**
   * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
   */
  @Override
  public JQuickFragmentProtoOrBuilder getFragmentOrBuilder() {
    return fragment_ == null ? JQuickFragmentProto.getDefaultInstance() : fragment_;
  }

  public static final int ASSIGNED_PARTITION_FIELD_NUMBER = 3;
  private JQuickMemoryPartitionProto assignedPartition_;
  /**
   * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
   * @return Whether the assignedPartition field is set.
   */
  @Override
  public boolean hasAssignedPartition() {
    return assignedPartition_ != null;
  }
  /**
   * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
   * @return The assignedPartition.
   */
  @Override
  public JQuickMemoryPartitionProto getAssignedPartition() {
    return assignedPartition_ == null ? JQuickMemoryPartitionProto.getDefaultInstance() : assignedPartition_;
  }
  /**
   * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
   */
  @Override
  public JQuickMemoryPartitionProtoOrBuilder getAssignedPartitionOrBuilder() {
    return assignedPartition_ == null ? JQuickMemoryPartitionProto.getDefaultInstance() : assignedPartition_;
  }

  public static final int PRIORITY_FIELD_NUMBER = 4;
  private int priority_ = 0;
  /**
   * <code>int32 priority = 4;</code>
   * @return The priority.
   */
  @Override
  public int getPriority() {
    return priority_;
  }

  public static final int MEMORY_LIMIT_FIELD_NUMBER = 5;
  private long memoryLimit_ = 0L;
  /**
   * <code>int64 memory_limit = 5;</code>
   * @return The memoryLimit.
   */
  @Override
  public long getMemoryLimit() {
    return memoryLimit_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
    }
    if (fragment_ != null) {
      output.writeMessage(2, getFragment());
    }
    if (assignedPartition_ != null) {
      output.writeMessage(3, getAssignedPartition());
    }
    if (priority_ != 0) {
      output.writeInt32(4, priority_);
    }
    if (memoryLimit_ != 0L) {
      output.writeInt64(5, memoryLimit_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
    }
    if (fragment_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFragment());
    }
    if (assignedPartition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAssignedPartition());
    }
    if (priority_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, priority_);
    }
    if (memoryLimit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, memoryLimit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof JQuickTaskAssignmentProto)) {
      return super.equals(obj);
    }
    JQuickTaskAssignmentProto other = (JQuickTaskAssignmentProto) obj;

    if (!getTaskId()
        .equals(other.getTaskId())) return false;
    if (hasFragment() != other.hasFragment()) return false;
    if (hasFragment()) {
      if (!getFragment()
          .equals(other.getFragment())) return false;
    }
    if (hasAssignedPartition() != other.hasAssignedPartition()) return false;
    if (hasAssignedPartition()) {
      if (!getAssignedPartition()
          .equals(other.getAssignedPartition())) return false;
    }
    if (getPriority()
        != other.getPriority()) return false;
    if (getMemoryLimit()
        != other.getMemoryLimit()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    if (hasFragment()) {
      hash = (37 * hash) + FRAGMENT_FIELD_NUMBER;
      hash = (53 * hash) + getFragment().hashCode();
    }
    if (hasAssignedPartition()) {
      hash = (37 * hash) + ASSIGNED_PARTITION_FIELD_NUMBER;
      hash = (53 * hash) + getAssignedPartition().hashCode();
    }
    hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + getPriority();
    hash = (37 * hash) + MEMORY_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMemoryLimit());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static JQuickTaskAssignmentProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JQuickTaskAssignmentProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JQuickTaskAssignmentProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JQuickTaskAssignmentProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JQuickTaskAssignmentProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JQuickTaskAssignmentProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JQuickTaskAssignmentProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JQuickTaskAssignmentProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static JQuickTaskAssignmentProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static JQuickTaskAssignmentProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static JQuickTaskAssignmentProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JQuickTaskAssignmentProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(JQuickTaskAssignmentProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 任务分配
   * </pre>
   *
   * Protobuf type {@code com.github.paohaijiao.proto.JQuickTaskAssignmentProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.paohaijiao.proto.JQuickTaskAssignmentProto)
      JQuickTaskAssignmentProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTaskAssignmentProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTaskAssignmentProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JQuickTaskAssignmentProto.class, Builder.class);
    }

    // Construct using com.github.paohaijiao.proto.JQuickTaskAssignmentProto.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      taskId_ = "";
      fragment_ = null;
      if (fragmentBuilder_ != null) {
        fragmentBuilder_.dispose();
        fragmentBuilder_ = null;
      }
      assignedPartition_ = null;
      if (assignedPartitionBuilder_ != null) {
        assignedPartitionBuilder_.dispose();
        assignedPartitionBuilder_ = null;
      }
      priority_ = 0;
      memoryLimit_ = 0L;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return JQuickPhysicalPlanProto.internal_static_com_github_paohaijiao_proto_JQuickTaskAssignmentProto_descriptor;
    }

    @Override
    public JQuickTaskAssignmentProto getDefaultInstanceForType() {
      return JQuickTaskAssignmentProto.getDefaultInstance();
    }

    @Override
    public JQuickTaskAssignmentProto build() {
      JQuickTaskAssignmentProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public JQuickTaskAssignmentProto buildPartial() {
      JQuickTaskAssignmentProto result = new JQuickTaskAssignmentProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(JQuickTaskAssignmentProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.taskId_ = taskId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fragment_ = fragmentBuilder_ == null
            ? fragment_
            : fragmentBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.assignedPartition_ = assignedPartitionBuilder_ == null
            ? assignedPartition_
            : assignedPartitionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.priority_ = priority_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.memoryLimit_ = memoryLimit_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof JQuickTaskAssignmentProto) {
        return mergeFrom((JQuickTaskAssignmentProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(JQuickTaskAssignmentProto other) {
      if (other == JQuickTaskAssignmentProto.getDefaultInstance()) return this;
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasFragment()) {
        mergeFragment(other.getFragment());
      }
      if (other.hasAssignedPartition()) {
        mergeAssignedPartition(other.getAssignedPartition());
      }
      if (other.getPriority() != 0) {
        setPriority(other.getPriority());
      }
      if (other.getMemoryLimit() != 0L) {
        setMemoryLimit(other.getMemoryLimit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              taskId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getFragmentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getAssignedPartitionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              priority_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              memoryLimit_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object taskId_ = "";
    /**
     * <code>string task_id = 1;</code>
     * @return The taskId.
     */
    public String getTaskId() {
      Object ref = taskId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string task_id = 1;</code>
     * @return The bytes for taskId.
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_id = 1;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      taskId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      taskId_ = getDefaultInstance().getTaskId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 1;</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      taskId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private JQuickFragmentProto fragment_;
    private com.google.protobuf.SingleFieldBuilderV3<
        JQuickFragmentProto, JQuickFragmentProto.Builder, JQuickFragmentProtoOrBuilder> fragmentBuilder_;
    /**
     * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
     * @return Whether the fragment field is set.
     */
    public boolean hasFragment() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
     * @return The fragment.
     */
    public JQuickFragmentProto getFragment() {
      if (fragmentBuilder_ == null) {
        return fragment_ == null ? JQuickFragmentProto.getDefaultInstance() : fragment_;
      } else {
        return fragmentBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
     */
    public Builder setFragment(JQuickFragmentProto value) {
      if (fragmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fragment_ = value;
      } else {
        fragmentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
     */
    public Builder setFragment(
        JQuickFragmentProto.Builder builderForValue) {
      if (fragmentBuilder_ == null) {
        fragment_ = builderForValue.build();
      } else {
        fragmentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
     */
    public Builder mergeFragment(JQuickFragmentProto value) {
      if (fragmentBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          fragment_ != null &&
          fragment_ != JQuickFragmentProto.getDefaultInstance()) {
          getFragmentBuilder().mergeFrom(value);
        } else {
          fragment_ = value;
        }
      } else {
        fragmentBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
     */
    public Builder clearFragment() {
      bitField0_ = (bitField0_ & ~0x00000002);
      fragment_ = null;
      if (fragmentBuilder_ != null) {
        fragmentBuilder_.dispose();
        fragmentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
     */
    public JQuickFragmentProto.Builder getFragmentBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getFragmentFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
     */
    public JQuickFragmentProtoOrBuilder getFragmentOrBuilder() {
      if (fragmentBuilder_ != null) {
        return fragmentBuilder_.getMessageOrBuilder();
      } else {
        return fragment_ == null ?
            JQuickFragmentProto.getDefaultInstance() : fragment_;
      }
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickFragmentProto fragment = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        JQuickFragmentProto, JQuickFragmentProto.Builder, JQuickFragmentProtoOrBuilder>
        getFragmentFieldBuilder() {
      if (fragmentBuilder_ == null) {
        fragmentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            JQuickFragmentProto, JQuickFragmentProto.Builder, JQuickFragmentProtoOrBuilder>(
                getFragment(),
                getParentForChildren(),
                isClean());
        fragment_ = null;
      }
      return fragmentBuilder_;
    }

    private JQuickMemoryPartitionProto assignedPartition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        JQuickMemoryPartitionProto, JQuickMemoryPartitionProto.Builder, JQuickMemoryPartitionProtoOrBuilder> assignedPartitionBuilder_;
    /**
     * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
     * @return Whether the assignedPartition field is set.
     */
    public boolean hasAssignedPartition() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
     * @return The assignedPartition.
     */
    public JQuickMemoryPartitionProto getAssignedPartition() {
      if (assignedPartitionBuilder_ == null) {
        return assignedPartition_ == null ? JQuickMemoryPartitionProto.getDefaultInstance() : assignedPartition_;
      } else {
        return assignedPartitionBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
     */
    public Builder setAssignedPartition(JQuickMemoryPartitionProto value) {
      if (assignedPartitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        assignedPartition_ = value;
      } else {
        assignedPartitionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
     */
    public Builder setAssignedPartition(
        JQuickMemoryPartitionProto.Builder builderForValue) {
      if (assignedPartitionBuilder_ == null) {
        assignedPartition_ = builderForValue.build();
      } else {
        assignedPartitionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
     */
    public Builder mergeAssignedPartition(JQuickMemoryPartitionProto value) {
      if (assignedPartitionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          assignedPartition_ != null &&
          assignedPartition_ != JQuickMemoryPartitionProto.getDefaultInstance()) {
          getAssignedPartitionBuilder().mergeFrom(value);
        } else {
          assignedPartition_ = value;
        }
      } else {
        assignedPartitionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
     */
    public Builder clearAssignedPartition() {
      bitField0_ = (bitField0_ & ~0x00000004);
      assignedPartition_ = null;
      if (assignedPartitionBuilder_ != null) {
        assignedPartitionBuilder_.dispose();
        assignedPartitionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
     */
    public JQuickMemoryPartitionProto.Builder getAssignedPartitionBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getAssignedPartitionFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
     */
    public JQuickMemoryPartitionProtoOrBuilder getAssignedPartitionOrBuilder() {
      if (assignedPartitionBuilder_ != null) {
        return assignedPartitionBuilder_.getMessageOrBuilder();
      } else {
        return assignedPartition_ == null ?
            JQuickMemoryPartitionProto.getDefaultInstance() : assignedPartition_;
      }
    }
    /**
     * <code>.com.github.paohaijiao.proto.JQuickMemoryPartitionProto assigned_partition = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        JQuickMemoryPartitionProto, JQuickMemoryPartitionProto.Builder, JQuickMemoryPartitionProtoOrBuilder>
        getAssignedPartitionFieldBuilder() {
      if (assignedPartitionBuilder_ == null) {
        assignedPartitionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            JQuickMemoryPartitionProto, JQuickMemoryPartitionProto.Builder, JQuickMemoryPartitionProtoOrBuilder>(
                getAssignedPartition(),
                getParentForChildren(),
                isClean());
        assignedPartition_ = null;
      }
      return assignedPartitionBuilder_;
    }

    private int priority_ ;
    /**
     * <code>int32 priority = 4;</code>
     * @return The priority.
     */
    @Override
    public int getPriority() {
      return priority_;
    }
    /**
     * <code>int32 priority = 4;</code>
     * @param value The priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriority(int value) {
      
      priority_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 priority = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriority() {
      bitField0_ = (bitField0_ & ~0x00000008);
      priority_ = 0;
      onChanged();
      return this;
    }

    private long memoryLimit_ ;
    /**
     * <code>int64 memory_limit = 5;</code>
     * @return The memoryLimit.
     */
    @Override
    public long getMemoryLimit() {
      return memoryLimit_;
    }
    /**
     * <code>int64 memory_limit = 5;</code>
     * @param value The memoryLimit to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryLimit(long value) {
      
      memoryLimit_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 memory_limit = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryLimit() {
      bitField0_ = (bitField0_ & ~0x00000010);
      memoryLimit_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.paohaijiao.proto.JQuickTaskAssignmentProto)
  }

  // @@protoc_insertion_point(class_scope:com.github.paohaijiao.proto.JQuickTaskAssignmentProto)
  private static final JQuickTaskAssignmentProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new JQuickTaskAssignmentProto();
  }

  public static JQuickTaskAssignmentProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JQuickTaskAssignmentProto>
      PARSER = new com.google.protobuf.AbstractParser<JQuickTaskAssignmentProto>() {
    @Override
    public JQuickTaskAssignmentProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JQuickTaskAssignmentProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<JQuickTaskAssignmentProto> getParserForType() {
    return PARSER;
  }

  @Override
  public JQuickTaskAssignmentProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

