// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

/**
 * <pre>
 * 聚合阶段
 * </pre>
 *
 * Protobuf enum {@code com.github.paohaijiao.proto.JQuickAggregateStageProto}
 */
public enum JQuickAggregateStageProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>AGG_PARTIAL = 0;</code>
   */
  AGG_PARTIAL(0),
  /**
   * <code>AGG_FINAL = 1;</code>
   */
  AGG_FINAL(1),
  /**
   * <code>AGG_SINGLE = 2;</code>
   */
  AGG_SINGLE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>AGG_PARTIAL = 0;</code>
   */
  public static final int AGG_PARTIAL_VALUE = 0;
  /**
   * <code>AGG_FINAL = 1;</code>
   */
  public static final int AGG_FINAL_VALUE = 1;
  /**
   * <code>AGG_SINGLE = 2;</code>
   */
  public static final int AGG_SINGLE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static JQuickAggregateStageProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static JQuickAggregateStageProto forNumber(int value) {
    switch (value) {
      case 0: return AGG_PARTIAL;
      case 1: return AGG_FINAL;
      case 2: return AGG_SINGLE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<JQuickAggregateStageProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      JQuickAggregateStageProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<JQuickAggregateStageProto>() {
          public JQuickAggregateStageProto findValueByNumber(int number) {
            return JQuickAggregateStageProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return JQuickPhysicalPlanProto.getDescriptor().getEnumTypes().get(6);
  }

  private static final JQuickAggregateStageProto[] VALUES = values();

  public static JQuickAggregateStageProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private JQuickAggregateStageProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.github.paohaijiao.proto.JQuickAggregateStageProto)
}

