// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

/**
 * Protobuf enum {@code com.github.paohaijiao.proto.JQuickBuildSideProto}
 */
public enum JQuickBuildSideProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>BUILD_SIDE_LEFT = 0;</code>
   */
  BUILD_SIDE_LEFT(0),
  /**
   * <code>BUILD_SIDE_RIGHT = 1;</code>
   */
  BUILD_SIDE_RIGHT(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>BUILD_SIDE_LEFT = 0;</code>
   */
  public static final int BUILD_SIDE_LEFT_VALUE = 0;
  /**
   * <code>BUILD_SIDE_RIGHT = 1;</code>
   */
  public static final int BUILD_SIDE_RIGHT_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static JQuickBuildSideProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static JQuickBuildSideProto forNumber(int value) {
    switch (value) {
      case 0: return BUILD_SIDE_LEFT;
      case 1: return BUILD_SIDE_RIGHT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<JQuickBuildSideProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      JQuickBuildSideProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<JQuickBuildSideProto>() {
          public JQuickBuildSideProto findValueByNumber(int number) {
            return JQuickBuildSideProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return JQuickPhysicalPlanProto.getDescriptor().getEnumTypes().get(4);
  }

  private static final JQuickBuildSideProto[] VALUES = values();

  public static JQuickBuildSideProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private JQuickBuildSideProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.github.paohaijiao.proto.JQuickBuildSideProto)
}

