// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

public interface SubmitQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.paohaijiao.proto.SubmitQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query_id = 1;</code>
   * @return The queryId.
   */
  String getQueryId();
  /**
   * <code>string query_id = 1;</code>
   * @return The bytes for queryId.
   */
  com.google.protobuf.ByteString
      getQueryIdBytes();

  /**
   * <code>string sql = 2;</code>
   * @return The sql.
   */
  String getSql();
  /**
   * <code>string sql = 2;</code>
   * @return The bytes for sql.
   */
  com.google.protobuf.ByteString
      getSqlBytes();

  /**
   * <code>map&lt;string, string&gt; parameters = 3;</code>
   */
  int getParametersCount();
  /**
   * <code>map&lt;string, string&gt; parameters = 3;</code>
   */
  boolean containsParameters(
      String key);
  /**
   * Use {@link #getParametersMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getParameters();
  /**
   * <code>map&lt;string, string&gt; parameters = 3;</code>
   */
  java.util.Map<String, String>
  getParametersMap();
  /**
   * <code>map&lt;string, string&gt; parameters = 3;</code>
   */
  /* nullable */
String getParametersOrDefault(
      String key,
      /* nullable */
String defaultValue);
  /**
   * <code>map&lt;string, string&gt; parameters = 3;</code>
   */
  String getParametersOrThrow(
      String key);

  /**
   * <code>int32 default_parallelism = 4;</code>
   * @return The defaultParallelism.
   */
  int getDefaultParallelism();
}
