// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/paohaijiao/distributed/proto/physical.proto

package com.github.paohaijiao.proto;

public interface JQuickQueryOptionsProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.paohaijiao.proto.JQuickQueryOptionsProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 timeout_seconds = 1;</code>
   * @return The timeoutSeconds.
   */
  int getTimeoutSeconds();

  /**
   * <code>int32 max_result_rows = 2;</code>
   * @return The maxResultRows.
   */
  int getMaxResultRows();

  /**
   * <code>bool collect_metrics = 3;</code>
   * @return The collectMetrics.
   */
  boolean getCollectMetrics();

  /**
   * <pre>
   * 内存限制（MB）
   * </pre>
   *
   * <code>int64 memory_limit_mb = 4;</code>
   * @return The memoryLimitMb.
   */
  long getMemoryLimitMb();

  /**
   * <pre>
   * 使用内存优化
   * </pre>
   *
   * <code>bool use_memory_optimized = 5;</code>
   * @return The useMemoryOptimized.
   */
  boolean getUseMemoryOptimized();
}
